<?php

use App\Category;
use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            [
                "id" => 1,
                "name" => "Root",
                "slug" => "name",
                "parent_id" => NULL,
                "featured" => 0,
                "menu" => 0,
                "niveau" => "1",
                "image" => NULL,
                "created_at" => "2021-06-02 16:04:48",
                "updated_at" => "2021-06-02 16:04:48",
            ],
            [
                "id" => 4,
                "name" => "Electronique",
                "slug" => "electronique",
                "parent_id" => 1,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "1",
                "image" => NULL,
                "created_at" => "2021-06-02 16:26:56",
                "updated_at" => "2021-06-02 18:43:13",
            ],
            [
                "id" => 17,
                "name" => "T�l�phones & Tablettes",
                "slug" => "telephones-tablettes",
                "parent_id" => 1,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "1",
                "image" => NULL,
                "created_at" => "2021-06-04 22:56:46",
                "updated_at" => "2021-06-04 22:56:46",
            ],
            [
                "id" => 48,
                "name" => "Informatique",
                "slug" => "informatique",
                "parent_id" => 1,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "1",
                "image" => NULL,
                "created_at" => "2021-06-04 23:22:29",
                "updated_at" => "2021-06-04 23:22:29",
            ],
            [
                "id" => 5,
                "name" => "Jeux Videos",
                "slug" => "jeux-videos",
                "parent_id" => 1,
                "featured" => 1,
                "menu" => 1,
                "niveau" => "1",
                "image" => NULL,
                "created_at" => "2021-06-02 18:01:17",
                "updated_at" => "2021-06-02 18:01:17",
            ],
            [
                "id" => 9,
                "name" => "Camera & photo",
                "slug" => "camera-photo",
                "parent_id" => 4,
                "featured" => 0,
                "menu" => 0,
                "niveau" => "2",
                "image" => NULL,
                "created_at" => "2021-06-02 20:25:09",
                "updated_at" => "2021-06-05 01:40:59",
            ],
            [
                "id" => 10,
                "name" => "T�l�vision",
                "slug" => "television",
                "parent_id" => 4,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "2",
                "image" => "categories/CT4pOlLs4R9COJOB0u66TyVvS.png",
                "created_at" => "2021-06-02 22:23:47",
                "updated_at" => "2021-06-04 23:05:22",
            ],
            [
                "id" => 11,
                "name" => "Audios & HIFI",
                "slug" => "audios-hifi",
                "parent_id" => 4,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "2",
                "image" => NULL,
                "created_at" => "2021-06-02 23:12:38",
                "updated_at" => "2021-06-04 23:11:12",
            ],
            [
                "id" => 37,
                "name" => "Consoles & PlayStations",
                "slug" => "consoles-playstations",
                "parent_id" => 5,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "2",
                "image" => NULL,
                "created_at" => "2021-06-04 23:15:39",
                "updated_at" => "2021-06-04 23:15:39",
            ],
            [
                "id" => 44,
                "name" => "Jeux PC",
                "slug" => "jeux-pc",
                "parent_id" => 5,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "2",
                "image" => NULL,
                "created_at" => "2021-06-04 23:20:14",
                "updated_at" => "2021-06-04 23:20:14",
            ],
            [
                "id" => 12,
                "name" => "Camera de surveillance",
                "slug" => "camera-de-surveillance",
                "parent_id" => 9,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-02 23:13:18",
                "updated_at" => "2021-06-04 23:09:11",
            ],
            [
                "id" => 13,
                "name" => "Appareils Photos",
                "slug" => "appareils-photos",
                "parent_id" => 9,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-02 23:13:46",
                "updated_at" => "2021-06-04 23:07:52",
            ],
            [
                "id" => 14,
                "name" => "Vid�os",
                "slug" => "videos",
                "parent_id" => 9,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-02 23:14:20",
                "updated_at" => "2021-06-04 23:07:14",
            ],
            [
                "id" => 15,
                "name" => "Objectif Photos",
                "slug" => "objectif-photos",
                "parent_id" => 9,
                "featured" => 0,
                "menu" => 0,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-02 23:14:48",
                "updated_at" => "2021-06-04 23:08:28",
            ],
            [
                "id" => 16,
                "name" => "Photos & Studio",
                "slug" => "photos-studio",
                "parent_id" => 9,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-02 23:15:22",
                "updated_at" => "2021-06-02 23:15:22",
            ],
            [
                "id" => 28,
                "name" => "Smart Tv",
                "slug" => "smart-tv",
                "parent_id" => 10,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:09:43",
                "updated_at" => "2021-06-04 23:09:43",
            ],
            [
                "id" => 29,
                "name" => "TV LED & LCD",
                "slug" => "tv-led-lcd",
                "parent_id" => 10,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:10:09",
                "updated_at" => "2021-06-04 23:10:09",
            ],
            [
                "id" => 30,
                "name" => "T�l�vision OLED",
                "slug" => "television-oled",
                "parent_id" => 10,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:10:37",
                "updated_at" => "2021-06-04 23:10:37",
            ],
            [
                "id" => 31,
                "name" => "Home Cin�ma",
                "slug" => "home-cinema",
                "parent_id" => 11,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:11:39",
                "updated_at" => "2021-06-04 23:11:39",
            ],
            [
                "id" => 32,
                "name" => "Haut-parleurs",
                "slug" => "haut-parleurs",
                "parent_id" => 11,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:12:02",
                "updated_at" => "2021-06-04 23:12:02",
            ],
            [
                "id" => 33,
                "name" => "Lecteur MP3 & IPod",
                "slug" => "lecteur-mp3-ipod",
                "parent_id" => 11,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:12:38",
                "updated_at" => "2021-06-04 23:12:38",
            ],
            [
                "id" => 34,
                "name" => "Radio R�veil",
                "slug" => "radio-reveil",
                "parent_id" => 11,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:13:03",
                "updated_at" => "2021-06-04 23:13:03",
            ],
            [
                "id" => 19,
                "name" => "Tablettes",
                "slug" => "tablettes",
                "parent_id" => 17,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "2",
                "image" => NULL,
                "created_at" => "2021-06-04 22:58:16",
                "updated_at" => "2021-06-04 22:58:16",
            ],
            [
                "id" => 20,
                "name" => "Accessoires T�l�phones",
                "slug" => "accessoires-telephones",
                "parent_id" => 17,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "1",
                "image" => NULL,
                "created_at" => "2021-06-04 22:59:14",
                "updated_at" => "2021-06-04 22:59:14",
            ],
            [
                "id" => 18,
                "name" => "T�l�phones portables",
                "slug" => "telephones-portables",
                "parent_id" => 17,
                "featured" => 1,
                "menu" => 1,
                "niveau" => "2",
                "image" => NULL,
                "created_at" => "2021-06-04 22:57:48",
                "updated_at" => "2021-06-04 22:57:48",
            ],
            [
                "id" => 23,
                "name" => "T�l�phone Basique",
                "slug" => "telephone-basique",
                "parent_id" => 18,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:00:45",
                "updated_at" => "2021-06-04 23:00:45",
            ],
            [
                "id" => 21,
                "name" => "Iphone",
                "slug" => "iphone",
                "parent_id" => 18,
                "featured" => 1,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 22:59:54",
                "updated_at" => "2021-06-05 00:02:34",
            ],
            [
                "id" => 22,
                "name" => "T�l�phone Android",
                "slug" => "telephone-android",
                "parent_id" => 18,
                "featured" => 1,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:00:26",
                "updated_at" => "2021-06-05 00:03:07",
            ],
            [
                "id" => 24,
                "name" => "Tablettes IPod",
                "slug" => "tablettes-ipod",
                "parent_id" => 19,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:01:23",
                "updated_at" => "2021-06-04 23:01:23",
            ],
            [
                "id" => 25,
                "name" => "Tablettes �ducatives",
                "slug" => "tablettes-educatives",
                "parent_id" => 19,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:01:51",
                "updated_at" => "2021-06-04 23:01:51",
            ],
            [
                "id" => 26,
                "name" => "Accessoires Tablettes",
                "slug" => "accessoires-tablettes",
                "parent_id" => 19,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:02:19",
                "updated_at" => "2021-06-04 23:02:19",
            ],
            [
                "id" => 27,
                "name" => "Autres Tablettes",
                "slug" => "autres-tablettes",
                "parent_id" => 19,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:02:54",
                "updated_at" => "2021-06-04 23:02:54",
            ],
            [
                "id" => 35,
                "name" => "PlayStation",
                "slug" => "playstation",
                "parent_id" => 37,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:14:31",
                "updated_at" => "2021-06-04 23:16:04",
            ],
            [
                "id" => 36,
                "name" => "Consoles PS4",
                "slug" => "consoles-ps4",
                "parent_id" => 37,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:15:01",
                "updated_at" => "2021-06-04 23:16:24",
            ],
            [
                "id" => 38,
                "name" => "Consoles PS3",
                "slug" => "consoles-ps3",
                "parent_id" => 37,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:16:56",
                "updated_at" => "2021-06-04 23:16:56",
            ],
            [
                "id" => 39,
                "name" => "Consoles Xbox",
                "slug" => "consoles-xbox",
                "parent_id" => 37,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:17:28",
                "updated_at" => "2021-06-04 23:17:28",
            ],
            [
                "id" => 40,
                "name" => "Consoles Nintendo",
                "slug" => "consoles-nintendo",
                "parent_id" => 37,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:18:04",
                "updated_at" => "2021-06-04 23:18:04",
            ],
            [
                "id" => 41,
                "name" => "Consoles PSP",
                "slug" => "consoles-psp",
                "parent_id" => 37,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:18:33",
                "updated_at" => "2021-06-04 23:18:33",
            ],
            [
                "id" => 42,
                "name" => "Jeux Xbox One",
                "slug" => "jeux-xbox-one",
                "parent_id" => 37,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:19:21",
                "updated_at" => "2021-06-04 23:19:21",
            ],
            [
                "id" => 43,
                "name" => "Jeux PS4",
                "slug" => "jeux-ps4",
                "parent_id" => 37,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:19:38",
                "updated_at" => "2021-06-04 23:19:38",
            ],
            [
                "id" => 45,
                "name" => "Mat�riels de jeux",
                "slug" => "materiels-de-jeux",
                "parent_id" => 44,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:20:51",
                "updated_at" => "2021-06-04 23:20:51",
            ],
            [
                "id" => 46,
                "name" => "Mat�riels de jeux Gamer",
                "slug" => "materiels-de-jeux-gamer",
                "parent_id" => 44,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:21:15",
                "updated_at" => "2021-06-04 23:21:15",
            ],
            [
                "id" => 47,
                "name" => "Accessoires",
                "slug" => "accessoires",
                "parent_id" => 44,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:21:41",
                "updated_at" => "2021-06-04 23:21:41",
            ],
            [
                "id" => 57,
                "name" => "Logiciels",
                "slug" => "logiciels",
                "parent_id" => 48,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "2",
                "image" => NULL,
                "created_at" => "2021-06-04 23:27:47",
                "updated_at" => "2021-06-04 23:27:47",
            ],
            [
                "id" => 60,
                "name" => "P�riph�riques & accessoires",
                "slug" => "peripheriques-accessoires",
                "parent_id" => 48,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "2",
                "image" => NULL,
                "created_at" => "2021-06-04 23:29:20",
                "updated_at" => "2021-06-04 23:29:20",
            ],
            [
                "id" => 66,
                "name" => "Stockage de donn�es",
                "slug" => "stockage-de-donnees",
                "parent_id" => 48,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:33:09",
                "updated_at" => "2021-06-04 23:33:09",
            ],
            [
                "id" => 49,
                "name" => "Ordinateurs",
                "slug" => "ordinateurs",
                "parent_id" => 48,
                "featured" => 1,
                "menu" => 1,
                "niveau" => "2",
                "image" => NULL,
                "created_at" => "2021-06-04 23:22:53",
                "updated_at" => "2021-06-05 00:24:04",
            ],
            [
                "id" => 54,
                "name" => "Imprimantes & Scanners",
                "slug" => "imprimantes-scanners",
                "parent_id" => 48,
                "featured" => 1,
                "menu" => 1,
                "niveau" => "2",
                "image" => NULL,
                "created_at" => "2021-06-04 23:25:15",
                "updated_at" => "2021-06-05 01:42:35",
            ],
            [
                "id" => 53,
                "name" => "Ecrans PC",
                "slug" => "ecrans-pc",
                "parent_id" => 49,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:24:28",
                "updated_at" => "2021-06-04 23:24:28",
            ],
            [
                "id" => 50,
                "name" => "Ordinateurs portables",
                "slug" => "ordinateurs-portables",
                "parent_id" => 49,
                "featured" => 1,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:23:20",
                "updated_at" => "2021-06-05 00:24:38",
            ],
            [
                "id" => 51,
                "name" => "MacBook",
                "slug" => "macbook",
                "parent_id" => 49,
                "featured" => 1,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:23:37",
                "updated_at" => "2021-06-05 00:25:15",
            ],
            [
                "id" => 52,
                "name" => "Ordinateurs de bureau",
                "slug" => "ordinateurs-de-bureau",
                "parent_id" => 49,
                "featured" => 1,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:24:05",
                "updated_at" => "2021-06-05 00:46:41",
            ],
            [
                "id" => 56,
                "name" => "Encre d'imprimantes et toner",
                "slug" => "encre-dimprimantes-et-toner",
                "parent_id" => 54,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:27:15",
                "updated_at" => "2021-06-04 23:27:15",
            ],
            [
                "id" => 55,
                "name" => "imprimantes et scanners",
                "slug" => "imprimantes-et-scanners",
                "parent_id" => 54,
                "featured" => 1,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:26:26",
                "updated_at" => "2021-06-05 01:41:42",
            ],
            [
                "id" => 58,
                "name" => "Anti-virus et s�curit�",
                "slug" => "anti-virus-et-securite",
                "parent_id" => 57,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:28:14",
                "updated_at" => "2021-06-04 23:28:14",
            ],
            [
                "id" => 59,
                "name" => "Licences Windows",
                "slug" => "licences-windows",
                "parent_id" => 57,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:28:36",
                "updated_at" => "2021-06-04 23:28:36",
            ],
            [
                "id" => 61,
                "name" => "Claviers & Souris Pc",
                "slug" => "claviers-souris-pc",
                "parent_id" => 60,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:29:52",
                "updated_at" => "2021-06-04 23:29:52",
            ],
            [
                "id" => 62,
                "name" => "Solutions r�seaux",
                "slug" => "solutions-reseaux",
                "parent_id" => 60,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:30:21",
                "updated_at" => "2021-06-04 23:30:21",
            ],
            [
                "id" => 63,
                "name" => "Composants informatiques",
                "slug" => "composants-informatiques",
                "parent_id" => 60,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:31:05",
                "updated_at" => "2021-06-04 23:31:05",
            ],
            [
                "id" => 64,
                "name" => "Chargeurs & adaptateurs",
                "slug" => "chargeurs-adaptateurs",
                "parent_id" => 60,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:31:35",
                "updated_at" => "2021-06-04 23:31:35",
            ],
            [
                "id" => 65,
                "name" => "Sacs & Housse",
                "slug" => "sacs-housse",
                "parent_id" => 60,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:32:09",
                "updated_at" => "2021-06-04 23:32:09",
            ],
            [
                "id" => 67,
                "name" => "Cl�s USB",
                "slug" => "cles-usb",
                "parent_id" => 66,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:33:37",
                "updated_at" => "2021-06-04 23:33:37",
            ],
            [
                "id" => 68,
                "name" => "Cartes m�moires",
                "slug" => "cartes-memoires",
                "parent_id" => 66,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:34:02",
                "updated_at" => "2021-06-04 23:34:02",
            ],
            [
                "id" => 69,
                "name" => "Disques durs externes",
                "slug" => "disques-durs-externes",
                "parent_id" => 66,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:34:28",
                "updated_at" => "2021-06-04 23:34:28",
            ],
            [
                "id" => 70,
                "name" => "Disques durs internes",
                "slug" => "disques-durs-internes",
                "parent_id" => 66,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:34:45",
                "updated_at" => "2021-06-04 23:34:45",
            ],
            [
                "id" => 71,
                "name" => "Disques durs SSD",
                "slug" => "disques-durs-ssd",
                "parent_id" => 66,
                "featured" => 0,
                "menu" => 1,
                "niveau" => "3",
                "image" => NULL,
                "created_at" => "2021-06-04 23:35:00",
                "updated_at" => "2021-06-04 23:35:00",
            ],
        ];
         
        foreach($categories as $categorie){
            Category::create($categorie);
        }
        
    }
}
