<?php

use App\Product;
use App\ProductImage;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            [
                "id" => 10,
                "brand_id" => 0,
                "sku" => "PR-0001",
                "name" => "Produit 1",
                "slug" => "produit-1",
                "description" => NULL,
                "caracteristique" => NULL,
                "quantity" => 10,
                "price" => 10000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 1,
                "stock" => NULL,
                "is_new" => 1,
                "product_image" => "DcX9o2h8Uh7c6RTG4QtAhRpFU.jpg",
                "created_at" => "2021-06-03 09:15:16",
                "updated_at" => "2021-06-03 10:56:13",
                "height" => 10,
            ],
            [
                "id" => 11,
                "brand_id" => 0,
                "sku" => "PR-0002",
                "name" => "Produit 2",
                "slug" => "produit-2",
                "description" => NULL,
                "caracteristique" => NULL,
                "quantity" => 50,
                "price" => 10000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 1,
                "stock" => 5,
                "is_new" => 0,
                "product_image" => "81Oja4NXiEjbh0GqC7CsfkX0m.jpg",
                "created_at" => "2021-06-03 10:16:29",
                "updated_at" => "2021-06-03 10:16:29",
                "height" => NULL,
            ],
            [
                "id" => 13,
                "brand_id" => 0,
                "sku" => "PR-0003",
                "name" => "Produit 3",
                "slug" => "produit-3",
                "description" => NULL,
                "caracteristique" => NULL,
                "quantity" => 50,
                "price" => 10000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 1,
                "stock" => 5,
                "is_new" => 1,
                "product_image" => "htmPyPAUH2tELxisVOM6Ahq68.jpg",
                "created_at" => "2021-06-03 10:18:57",
                "updated_at" => "2021-06-03 10:51:21",
                "height" => NULL,
            ],
            [
                "id" => 14,
                "brand_id" => 0,
                "sku" => "PR-0004",
                "name" => "Produit 4",
                "slug" => "produit-4",
                "description" => NULL,
                "caracteristique" => NULL,
                "quantity" => 5,
                "price" => 30000,
                "sale_price" => 25000,
                "status" => 1,
                "featured" => 1,
                "stock" => 2,
                "is_new" => 0,
                "product_image" => "mmxlTUvv4rAj2lUNbIhvojPfK.jpg",
                "created_at" => "2021-06-03 12:34:33",
                "updated_at" => "2021-06-03 12:34:33",
                "height" => NULL,
            ],
            [
                "id" => 15,
                "brand_id" => 0,
                "sku" => "PR-0005",
                "name" => "Produit 5",
                "slug" => "produit-5",
                "description" => NULL,
                "caracteristique" => NULL,
                "quantity" => 20,
                "price" => 33000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 2,
                "is_new" => 1,
                "product_image" => "NADfXIJoOrkGD4Oqx5cUtAJCB.jpg",
                "created_at" => "2021-06-03 12:58:46",
                "updated_at" => "2021-06-03 12:58:46",
                "height" => NULL,
            ],
            [
                "id" => 16,
                "brand_id" => 0,
                "sku" => "PR-0001",
                "name" => "Samsung Galaxy A12- 4G - 6.4\" - 4/64Go - 13Mpx - Noir - Garantie 24 Mois",
                "slug" => "samsung-galaxy-a12-4g-64-464go-13mpx-noir-garantie-24-mois",
                "description" => "<p><strong>Le Samsung Galaxy A12</strong>&nbsp;annonc&eacute; par la firme le 13 mars 2020 est un entr&eacute;e de gamme embarquant un SoC Exynos 7904 &eacute;paul&eacute; par 2 ou 3 Go de RAM et 32 Go de stockage, extensible par microSD. Il poss&egrave;de un triple capteur au dos avec le principal &agrave; 13 m&eacute;gapixels. Il a une batterie de 4000 mAh compatible charge rapide (15 W).Le Samsung Galaxy A12 annonc&eacute; par la firme le 13 mars 2020 est un entr&eacute;e de gamme embarquant un SoC Exynos 7904 &eacute;paul&eacute; par 2 ou 3 Go de RAM et 32 Go de stockage, extensible par microSD. Il poss&egrave;de un triple capteur au dos avec le principal &agrave; 13 m&eacute;gapixels. Il a une batterie de 4000 mAh compatible charge rapide (15 W).<strong>Le Samsung Galaxy A12</strong>&nbsp;annonc&eacute; par la firme le 13 mars 2020 est un entr&eacute;e de gamme embarquant un SoC Exynos 7904 &eacute;paul&eacute; par 2 ou 3 Go de RAM et 32 Go de stockage, extensible par microSD. Il poss&egrave;de un triple capteur au dos avec le principal &agrave; 13 m&eacute;gapixels. Il a une batterie de 4000 mAh compatible charge rapide (15 W).</p>",
                "caracteristique" => "<ul>\r\n<li>M&eacute;moire Interne: 64 GB</li>\r\n<li>M&eacute;moire Ram: 4GB</li>\r\n<li>Appareil Photo Arri&egrave;re: 13 Mpx</li>\r\n<li>Ecran: 6.4 Pouces</li>\r\n<li>Affichage:&nbsp;Super AMOLED Plus capacitive touchscreen, 16M colors</li>\r\n<li>Syst&egrave;me d,exploitation:&nbsp;Android 10.0; One UI 2</li>\r\n<li>Cpu:&nbsp;Octa-core (2x2.2 GHz Kryo 470 Gold &amp; 6x1.8 GHz Kryo 470 Silver)</li>\r\n<li>R&eacute;seau: 4G LTE</li>\r\n<li>Sim: Dual Sim</li>\r\n<li>Batterie:&nbsp;Non-removable Li-Po 4000 mAh battery</li>\r\n<li>Type de Produit:Smartphone&nbsp;</li>\r\n<li>Garantie:24Mois&nbsp;</li>\r\n</ul>",
                "quantity" => 50,
                "price" => 78950,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 10,
                "is_new" => 1,
                "product_image" => "1FDt4I4sWYwuJ7jI65rpxLjVB.jpg",
                "created_at" => "2021-06-04 23:42:19",
                "updated_at" => "2021-06-04 23:42:19",
                "height" => NULL,
            ],
            [
                "id" => 17,
                "brand_id" => 0,
                "sku" => "AP009MP1G1521NAFAMZ",
                "name" => "Apple IPhone 6 - 4.7\" - 1Go - 16Go - 8Mpx - 4G - Or - Reconditionn� - Garantie 3 Mois",
                "slug" => "apple-iphone-6-47-1go-16go-8mpx-4g-or-reconditionne-garantie-3-mois",
                "description" => "<h2><strong><em>Reconditionn&eacute; d&eacute;signe un produit qui a &eacute;t&eacute; remis sur le march&eacute; apr&egrave;s avoir &eacute;t&eacute; sorti de son emballage mais pas utilis&eacute;. Le plus souvent, il s'agit d'un mat&eacute;riel qui pr&eacute;sentait un probl&egrave;me ou une panne et qui a &eacute;t&eacute; r&eacute;par&eacute;.</em></strong></h2>\r\n<p>L&rsquo;iPhone 6 n&rsquo;est pas seulement plus grand en taille. Il est plus grand en tout. Plus large, mais beaucoup plus fin. Plus puissant, mais remarquablement &eacute;conome en &eacute;nergie. Sa surface lisse m&eacute;tallique &eacute;pouse &agrave; merveille le nouvel &eacute;cran Retina HD. Sous son design profil&eacute; s&rsquo;op&egrave;re une fusion parfaite entre mat&eacute;riel et logiciel. Redessin&eacute;e, aff&ucirc;t&eacute;e, perfectionn&eacute;e, une nouvelle g&eacute;n&eacute;ration d&rsquo;iPhone est n&eacute;e.&nbsp;<br />L&rsquo;iPhone n&rsquo;a jamais &eacute;t&eacute; aussi grand. Ni aussi fin.</p>",
                "caracteristique" => "<ul>\r\n<li>Garantie : 3 Mois</li>\r\n<li><strong><em>Reconditionn&eacute;</em></strong></li>\r\n<li>Type de produit : Smartphone</li>\r\n<li>Mod&egrave;le : iPhone 6</li>\r\n<li>&Eacute;cran : 4,7\" LCD Retina HD</li>\r\n<li>R&eacute;solution: 1334x750</li>\r\n<li>Camera principale : 8 M&eacute;gaPixels avec ouverture f/2.2 pour le capteur dorsal, et</li>\r\n<li>Camera secondaire : 1,2 MPixels pour la capteur frontal</li>\r\n<li>Syst&egrave;me d'exploitation : iOS 8</li>\r\n<li>Processeur : Processeur A8 avec architecture 64-bit</li>\r\n<li>Connexion : Volte, Wifi AC, NFC, Bluetooth 4.0, 4G LTE</li>\r\n<li>M&eacute;moire ROM : 16 Go</li>\r\n<li>M&eacute;moire RAM: 1 Go</li>\r\n<li>Autonomie : Batterie au Lithium-ion avec 10 jours d'autonomie en veille</li>\r\n<li>Dimensions : 138,1x67x6,9 mm</li>\r\n</ul>\r\n<ul>\r\n<li>MARCORY REMBLAIS NON LOIN DU FEU DE L'EGLISE CATHOLIQUE STE BERNADETTE / Tel: 21 26 07 68 Cel: 88 21 21 59 / 02 21 21 49</li>\r\n</ul>",
                "quantity" => 10,
                "price" => 62900,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 5,
                "is_new" => 1,
                "product_image" => "RaS3tcMZfEfCzufNu87AJZq4Q.jpg",
                "created_at" => "2021-06-04 23:46:45",
                "updated_at" => "2021-06-04 23:46:45",
                "height" => NULL,
            ],
            [
                "id" => 18,
                "brand_id" => 0,
                "sku" => "AP009MP1ELYJHNAFAMZ",
                "name" => "Apple IPhone 8 - 4.7 \" - 4G LTE - 64Go - 2Go - 12Mpx - Noir",
                "slug" => "apple-iphone-8-47-4g-lte-64go-2go-12mpx-noir",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>Type de produit : Smartphone</li>\r\n<li>Mod&egrave;le: Iphone 8</li>\r\n<li>Ecran: 4.7 Pouces LCD</li>\r\n<li>R&eacute;tine</li>\r\n<li>int&egrave;gre la puce: Nano-Sim</li>\r\n<li>Processeur: Apple11 Bionic</li>\r\n<li>Syst&egrave;me d'exploitation: IOS 11</li>\r\n<li>M&eacute;moire RAM: 2 Go</li>\r\n<li>M&eacute;moire Interne: 64 Go</li>\r\n<li>Touch ID: oui</li>\r\n<li>iTunes: 12,7</li>\r\n<li>iOS: 11</li>\r\n<li>Appareil photo Arri&egrave;re: 12 M&eacute;gapixels</li>\r\n<li>Appareil photo Avant: 7</li>\r\n<li>M&eacute;gapixels</li>\r\n<li>Cam&eacute;ra FaceTime: HD 7</li>\r\n<li>m&eacute;gapixels</li>\r\n<li>Connectivit&eacute;: LTE 3G + 4G</li>\r\n<li>iOS 11 ultra-rapide</li>\r\n</ul>",
                "quantity" => 10,
                "price" => 149900,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 2,
                "is_new" => 1,
                "product_image" => "MBxPw9ZsPDLFG9mwoV51SMIlE.jpg",
                "created_at" => "2021-06-04 23:49:15",
                "updated_at" => "2021-06-04 23:49:15",
                "height" => 0.2,
            ],
            [
                "id" => 19,
                "brand_id" => 0,
                "sku" => "AP009MP02MD95NAFAMZ",
                "name" => "Apple IPhone Xs � 5.8\" - 4G - 64Go - 4Go - 12Mpx - Silver",
                "slug" => "apple-iphone-xs-58-4g-64go-4go-12mpx-silver",
                "description" => "<h2 class=\"pd-billboard-header pd-util-compact-large-12 pd-util-compact-small-13\">Offrez vous L'une de ses merveilles &agrave; la pointe de le technologie !</h2>\r\n<ul>\r\n<li>Type de produit: Iphone Xs&nbsp;</li>\r\n<li>Taille d'&eacute;cran: 5.8 pouces&nbsp;</li>\r\n<li>Type de processeur: Pomme A11 Hexa-Core bionique&nbsp;</li>\r\n<li>M&eacute;moire: 64 Go&nbsp;</li>\r\n<li>Taille m&eacute;moire RAM: 4 Go&nbsp;</li>\r\n<li>Capacitif tactile &Eacute;cran Super AMOLED, 16M&nbsp;</li>\r\n<li>Carte sim: Nano-SIM et e-SIM&nbsp;</li>\r\n<li>IP68 r&eacute;sistant &agrave; l'eau et &agrave; la poussi&egrave;re (jusqu'&agrave; 2 m pendant 30 min)&nbsp;</li>\r\n<li>S&eacute;curit&eacute;: Reconnaissance faciale&nbsp;</li>\r\n<li>R&eacute;solution: 12 m&eacute;gapixels&nbsp;</li>\r\n<li>Syst&egrave;me d'exploitation: Apple iOS 12&nbsp;</li>\r\n<li>NFC: Oui&nbsp;</li>\r\n</ul>",
                "caracteristique" => "<ul>\r\n<li>Type de produit: Iphone Xs</li>\r\n<li>Taille d'&eacute;cran: 5.8 pouces</li>\r\n<li>Type de processeur: Pomme A11 Hexa-Core bionique</li>\r\n<li>M&eacute;moire: 64 Go</li>\r\n<li>Taille m&eacute;moire RAM: 4 Go</li>\r\n<li>Capacitif tactile &Eacute;cran Super AMOLED, 16M</li>\r\n<li>Carte sim: Nano-SIM et e-SIM</li>\r\n<li>IP68 r&eacute;sistant &agrave; l'eau et &agrave; la poussi&egrave;re (jusqu'&agrave; 2 m pendant 30 min)</li>\r\n<li>S&eacute;curit&eacute;: Reconnaissance faciale</li>\r\n<li>R&eacute;solution: 12 m&eacute;gapixels</li>\r\n<li>Syst&egrave;me d'exploitation: Apple iOS 12</li>\r\n<li>NFC: Oui</li>\r\n</ul>",
                "quantity" => 10,
                "price" => 271200,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 1,
                "stock" => 2,
                "is_new" => 1,
                "product_image" => "pgkQRBQD93qhhLV8Y9c3jXVuK.jpg",
                "created_at" => "2021-06-04 23:51:57",
                "updated_at" => "2021-06-04 23:52:26",
                "height" => 0.3,
            ],
            [
                "id" => 20,
                "brand_id" => 0,
                "sku" => "AP009EL1JP529NAFAMZ",
                "name" => "Apple IPhone XR- 6.1\"- 64 Go- IOS 12- 12 Mpx- 4G - Jaune",
                "slug" => "apple-iphone-xr-61-64-go-ios-12-12-mpx-4g-jaune",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>Type de produit : Iphone</li>\r\n<li>Mod&egrave;le ; Iphone XR</li>\r\n<li>Version de l'OS : iOS 12</li>\r\n<li>Interface : iOS</li>\r\n<li>Taille d'&eacute;cran : 6,1 pouces</li>\r\n<li>D&eacute;finition : 1792 x 828 pixels</li>\r\n<li>M&eacute;moire vive (RAM) : 3 Go</li>\r\n<li>M&eacute;moire interne (flash) : 64 Go</li>\r\n<li>Appareil photo (dorsal) : 12 M&eacute;gapixels</li>\r\n<li>Appareil photo (frontal) : 7 M&eacute;gapixels</li>\r\n<li>Enregistrement vid&eacute;o : 4K</li>\r\n</ul>",
                "quantity" => 20,
                "price" => 244000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 2,
                "is_new" => 1,
                "product_image" => "tdFjVRcPIUXoXZ6cG3E51gHsH.jpg",
                "created_at" => "2021-06-04 23:55:35",
                "updated_at" => "2021-06-04 23:55:35",
                "height" => NULL,
            ],
            [
                "id" => 21,
                "brand_id" => 0,
                "sku" => "AP009MP02N4Q1NAFAMZ",
                "name" => "Apple IPhone 12 Pro (128 Go) - Bleu - 12 Mois De Garantie",
                "slug" => "apple-iphone-12-pro-128-go-bleu-12-mois-de-garantie",
                "description" => NULL,
                "caracteristique" => "<ul class=\"a-unordered-list a-vertical a-spacing-none\">\r\n<li>Type de produit : Iphone</li>\r\n<li>Mod&egrave;le : 11 pro</li>\r\n<li>Capacit&eacute; de stockage 128 Go</li>\r\n<li>Ram : 4Go</li>\r\n<li>Syst&egrave;me d&rsquo;exploitation iOS 13</li>\r\n<li>&Eacute;cran OLED Super Retina XDR 5,8 &Prime; pouces</li>\r\n<li>R&eacute;sistant &agrave; la poussi&egrave;re et &agrave; l&rsquo;eau (jusqu&rsquo;&agrave; 4 m&egrave;tres pendant 30 minutes maximum, IP68)</li>\r\n<li>Triple appareil photo avec ultra grand-angle, grand-angle et t&eacute;l&eacute;objectif 12 Mpx, mode Nuit, mode Portrait et vid&eacute;o 4K jusqu&rsquo;&agrave; 60 i/s</li>\r\n<li>Cam&eacute;ra avant TrueDepth 12 Mpx avec mode Portrait, vid&eacute;o 4K et ralenti</li>\r\n<li>Face ID pour l&rsquo;authentification s&eacute;curis&eacute;e et Apple Pay</li>\r\n<li>Puce A13 Bionic avec Neural Engine de troisi&egrave;me g&eacute;n&eacute;ration</li>\r\n<li>Fr&eacute;quence du processeur : 2.65 GHz</li>\r\n<li>CPU : Octa-Core</li>\r\n<li>Cam&eacute;ra : 12 Mpx/12 Mpx/12 Mpx</li>\r\n<li>Nombre de capteurs (arri&egrave;re et avant) : 4</li>\r\n<li>Recharge rapide avec l&rsquo;adaptateur 18 W fourni</li>\r\n<li>Recharge sans fil</li>\r\n</ul>",
                "quantity" => 10,
                "price" => 779000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 1,
                "stock" => 2,
                "is_new" => 1,
                "product_image" => "UoFVumOmxXEGoUFB2CYYtR967.jpg",
                "created_at" => "2021-06-04 23:58:37",
                "updated_at" => "2021-06-04 23:58:37",
                "height" => NULL,
            ],
            [
                "id" => 22,
                "brand_id" => 0,
                "sku" => "AP009EL09TX4ANAFAMZ",
                "name" => "Apple IPhone XR- 6.1\"- 12 Mpx- 64 Go- IOS 12- 4G- Noir - Garantysmart 3 Mois",
                "slug" => "apple-iphone-xr-61-12-mpx-64-go-ios-12-4g-noir-garantysmart-3-mois",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>GarantySmart 3 Mois</li>\r\n<li>GarantySmart 3 Mois</li>\r\n<li>Type de Produit: Iphone</li>\r\n<li>Version de l'OS: iOS 12</li>\r\n<li>Interface: iOS</li>\r\n<li>Taille d'&eacute;cran: 6, 1 pouces</li>\r\n<li>D&eacute;finition: 1792 x 828 pixels</li>\r\n<li>M&eacute;moire vive (RAM): 3 Go</li>\r\n<li>M&eacute;moire interne (flash): 128 Go<br />li&gt; Appareil photo (dorsal): 12 M&eacute;gapixels</li>\r\n<li>Appareil photo (frontal): 7 M&eacute;gapixels</li>\r\n<li>Enregistrement vid&eacute;o: 4K</li>\r\n</ul>",
                "quantity" => 2,
                "price" => 244000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 1,
                "is_new" => 0,
                "product_image" => "KwSm754TScvLT3dnOFoCl0HVb.jpg",
                "created_at" => "2021-06-05 00:00:46",
                "updated_at" => "2021-06-05 00:00:46",
                "height" => NULL,
            ],
            [
                "id" => 23,
                "brand_id" => 0,
                "sku" => "TE292MP0ECQVXNAFAMZ",
                "name" => "Tecno POP 4 - 6\" - 3G - 2Go - 32Go - 8MP/5MP - 5000 MAH - Vert",
                "slug" => "tecno-pop-4-6-3g-2go-32go-8mp5mp-5000-mah-vert",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>Type de produit : Smartphone</li>\r\n<li>Mod&egrave;le : Pop 4</li>\r\n<li>Ecran : 6'Pouces</li>\r\n<li>Camera frontale : 8MP</li>\r\n<li>Camera Principale: 5 MP</li>\r\n<li>M&eacute;moire RAM : 2 Go</li>\r\n<li>M&eacute;moire ROM : 32</li>\r\n<li>Processeur : Quad-core</li>\r\n<li>Android 9.0</li>\r\n<li>Vitesse de processeur : 1.8 GHz Cortex-A53</li>\r\n<li>Connectivit&eacute;s : Bluetooth, R&eacute;seau 3G, microUSB 2.0, Radio</li>\r\n<li>S&eacute;curit&eacute; : Empreinte Digitale</li>\r\n<li>Batterie : 5000 mAh</li>\r\n</ul>",
                "quantity" => 10,
                "price" => 44500,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 2,
                "is_new" => 1,
                "product_image" => "zdkRIPLtAbNHjph0nwynSwAlY.jpg",
                "created_at" => "2021-06-05 00:05:41",
                "updated_at" => "2021-06-05 00:05:41",
                "height" => NULL,
            ],
            [
                "id" => 24,
                "brand_id" => 0,
                "sku" => "SA024MP0OBMBNNAFAMZ",
                "name" => "Samsung Galaxy A11- 4G - 6.4\" - 2/32Go - 13Mpx - Garantie 24 Mois - BLEU",
                "slug" => "samsung-galaxy-a11-4g-64-232go-13mpx-garantie-24-mois-bleu",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>M&eacute;moire Interne: 32 GB</li>\r\n<li>M&eacute;moire Ram: 2GB</li>\r\n<li>Appareil Photo Arri&egrave;re: 13 Mpx</li>\r\n<li>Ecran: 6.4 Pouces</li>\r\n<li>Affichage:&nbsp;Super AMOLED Plus capacitive touchscreen, 16M colors</li>\r\n<li>Syst&egrave;me d,exploitation:&nbsp;Android 10.0; One UI 2</li>\r\n<li>Cpu:&nbsp;Octa-core (2x2.2 GHz Kryo 470 Gold &amp; 6x1.8 GHz Kryo 470 Silver)</li>\r\n<li>R&eacute;seau: 4G LTE</li>\r\n<li>Sim: Dual Sim</li>\r\n<li>Batterie:&nbsp;Non-removable Li-Po 4000 mAh battery</li>\r\n<li>Type de Produit:Smartphone&nbsp;</li>\r\n<li>Garantie:24Mois&nbsp;</li>\r\n</ul>",
                "quantity" => 12,
                "price" => 65500,
                "sale_price" => 58900,
                "status" => 1,
                "featured" => 1,
                "stock" => NULL,
                "is_new" => 0,
                "product_image" => "6NtwKYtIvbaN8r8NXsPxDOjQS.jpg",
                "created_at" => "2021-06-05 00:08:50",
                "updated_at" => "2021-06-05 00:08:50",
                "height" => NULL,
            ],
            [
                "id" => 25,
                "brand_id" => 0,
                "sku" => "IN805MP04UGFLNAFAMZ",
                "name" => "Infinix Smart HD � 6.1\"- 2Go � 32Go � 8Mpx � 5000mAh � Noir - Garantie 13 Mois",
                "slug" => "infinix-smart-hd-61-2go-32go-8mpx-5000mah-noir-garantie-13-mois",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>Garantie 13 Mois</li>\r\n<li>Type de produit : Smartphone</li>\r\n<li>Mod&egrave;le : Smart HD</li>\r\n<li>&Eacute;cran 6.1 pouces&nbsp;</li>\r\n<li>R&eacute;solution 720*1600</li>\r\n<li>Cam&eacute;ra&nbsp;:&nbsp;8Mpx</li>\r\n<li>M&eacute;moire Ram : 2Go</li>\r\n<li>M&eacute;moire Rom 32Go</li>\r\n<li>R&eacute;seau&nbsp;: 3G</li>\r\n<li>Batterie 4000mAh&nbsp;</li>\r\n<li>Empreinte digitale Oui</li>\r\n<li>Dimension 167*76*8.3</li>\r\n<li>Android 9 Pie Go &eacute;dition&nbsp;</li>\r\n<li>Connectivit&eacute; GPS, Wifi, BT</li>\r\n<li>Poids : 0.154Kg</li>\r\n</ul>",
                "quantity" => 10,
                "price" => 56000,
                "sale_price" => 48600,
                "status" => 1,
                "featured" => 0,
                "stock" => 2,
                "is_new" => 1,
                "product_image" => "GKLJz6xgkEzzZugaRhS1HIH2C.jpg",
                "created_at" => "2021-06-05 00:11:11",
                "updated_at" => "2021-06-05 00:11:11",
                "height" => NULL,
            ],
            [
                "id" => 26,
                "brand_id" => 0,
                "sku" => "SA024MP05RQYTNAFAMZ",
                "name" => "Samsung Galaxy A72- 4G - 6.7\" - 8/128Go - 64MP/12MP/5MP/5MP - Octa-core - Bleu - Garantie 24 Mois",
                "slug" => "samsung-galaxy-a72-4g-67-8128go-64mp12mp5mp5mp-octa-core-bleu-garantie-24-mois",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>Garantie : 24 Mois</li>\r\n<li>Type de produit : Smartphone</li>\r\n<li>Mod&egrave;le : A72</li>\r\n<li>Ecran : 6.7 Pouces</li>\r\n<li>Camera Principale: 64MP/12MP/5MP/5MP</li>\r\n<li>Camera Secondaire: 32MP</li>\r\n<li>R&eacute;seau: 4G</li>\r\n<li>M&eacute;moire ROM: 128Go</li>\r\n<li>M&eacute;moire RAM: 8Go</li>\r\n<li>Processeur: Octa-core (2x2.2 GHz Kryo 470 Gold &amp; 6x1.8 GHz Kryo 470 Silver)</li>\r\n<li>Connectivit&eacute; : Wifi, Bluetooth, FM radio, NFC</li>\r\n<li>Securit&eacute; : Empreinte digitale</li>\r\n<li>USB : 2.0 Type C</li>\r\n<li>Batterie : 4500mAh</li>\r\n</ul>",
                "quantity" => 5,
                "price" => 210000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 2,
                "is_new" => 1,
                "product_image" => "ADH9gons0guw9YgOxKMQeyje1.jpg",
                "created_at" => "2021-06-05 00:13:27",
                "updated_at" => "2021-06-05 00:13:27",
                "height" => NULL,
            ],
            [
                "id" => 27,
                "brand_id" => 0,
                "sku" => "HU830EL0XCE89NAFAMZ",
                "name" => "Huawei P30 Lite New Edition - 6,15\" - 24 Mpx - 6Go - 256 Go - Bleu",
                "slug" => "huawei-p30-lite-new-edition-615-24-mpx-6go-256-go-bleu",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>Type de produit : Smartphone</li>\r\n<li>Mod&egrave;le : P30 lite New Edition</li>\r\n<li>R&eacute;seau 4G/LTE</li>\r\n<li>Dual SIM : Oui</li>\r\n<li>&Eacute;cran : 6,15 pouces</li>\r\n<li>R&eacute;solution : 1080 x 2312 pixels</li>\r\n<li>Processeur : Octa-core (4x2.2 GHz Cortex-A73 &amp; 4x1.7 GHz Cortex-A53)</li>\r\n<li>M&eacute;moire RAM :6 Go</li>\r\n<li>M&eacute;moire ROM : 256 Go (jusqu'&agrave; 512Go)</li>\r\n<li>Camera arri&egrave;re : 48 + 8 + 2 M&eacute;gapixels</li>\r\n<li>Camera avant : 24 M&eacute;gapixels</li>\r\n<li>Syst&egrave;me d'exploitation : Android 9.0 (Pie], EMUI 9.0</li>\r\n<li>Connectivit&eacute;s : WIFI - Bluetooth - NFC - GPS</li>\r\n<li>Batterie : 3340 mAh</li>\r\n<li>Dimensions : 152.9 x 72.7 x 7.4 mm</li>\r\n<li>Poids : 159g</li>\r\n</ul>",
                "quantity" => 12,
                "price" => 200000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 1,
                "stock" => NULL,
                "is_new" => 1,
                "product_image" => "9uhgqBpyFBOUAfAa9Ly5kk1zh.jpg",
                "created_at" => "2021-06-05 00:16:16",
                "updated_at" => "2021-06-05 00:16:16",
                "height" => NULL,
            ],
            [
                "id" => 28,
                "brand_id" => 0,
                "sku" => "LE018CL04H94HNAFAMZ",
                "name" => "Asus VivoBook 12 - Dual Core - 128Go - E203M - Win10 Officiel - Gris - Garantie 6 Mois",
                "slug" => "asus-vivobook-12-dual-core-128go-e203m-win10-officiel-gris-garantie-6-mois",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>Type de produit : Ordinateur Portable</li>\r\n<li>Mod&egrave;le :&nbsp; E203M</li>\r\n<li>Processeur Processeur Intel&reg; Celeron&reg; N4000,&nbsp;1.1 GHz&nbsp;(4 Mo de cache, jusqu'&agrave; 2,6 GHz)<br />M&eacute;moire Ram : LPDDR4 4GB<br />Capacit&eacute; du disc dur : 128Go</li>\r\n<li>Afficher 11,6 &rsquo;// Ultra Slim 200nits // HD 1366 &times; 768 16: 9 // &Eacute;blouissement Cam&eacute;ra vid&eacute;o Cam&eacute;ra Web VGA (type fixe)</li>\r\n<li>Syst&egrave;me op&eacute;rateur Windows 10 (64 bits)</li>\r\n<li>Sans fil 802.11ac + Bluetooth 4.1 (double bande) 1 * 1 adaptateur pour courant alternatif &oslash;4.0 l'audio Haut-parleur int&eacute;gr&eacute; Batterie 42WHrs, 3S1P, Li-ion 3 cellules</li>\r\n<li>Poids 0,97 kg (sans batterie) Lan N / A</li>\r\n<li>Lecteur de cartes Type: Micro SD Port USB 2x USB 3.0 Interface 1x prise combin&eacute;e sortie casque et entr&eacute;e audio</li>\r\n<li>Dimension 28,6 (L) x 19,3 (P) x 2,14 ~ 2,14 (H)&nbsp;</li>\r\n</ul>",
                "quantity" => 10,
                "price" => 199000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 3,
                "is_new" => 1,
                "product_image" => "XV9ciMYzLQsYLzgoDgJqGuyyY.jpg",
                "created_at" => "2021-06-05 00:20:44",
                "updated_at" => "2021-06-05 00:20:44",
                "height" => NULL,
            ],
            [
                "id" => 29,
                "brand_id" => 0,
                "sku" => "HP017EL1BT7M1NAFAMZ",
                "name" => "Hp ProBook 440 G5 Core I3 4 GB / 1000 GB HDD 14 Pouces Tactile Win 10 64B - Gris",
                "slug" => "hp-probook-440-g5-core-i3-4-gb-1000-gb-hdd-14-pouces-tactile-win-10-64b-gris",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<ul>\r\n<li><strong>Type de produit : Ordinateur portable</strong></li>\r\n<li><strong>Gamme de processeurs</strong>&nbsp;: Processeur Intel&reg; Core&trade; i3 de 7e g&eacute;n&eacute;ration</li>\r\n<li><strong>M&eacute;moire&nbsp;</strong>: 4&nbsp;Go de m&eacute;moire SDRAM DDR4-2400 (1 x 4&nbsp;Go)</li>\r\n<li><strong>Disque interne</strong>&nbsp;: SATA 500&nbsp;Go, 7200&nbsp;tr/min</li>\r\n<li><strong>Ecran&nbsp;</strong>: &Eacute;cran HD SVA anti-reflets &agrave; r&eacute;tro&eacute;clairage LED d'une diagonale de 35,56 cm (14 po], 220 cd/m2, 45 % sRGB (1 366 x 768)</li>\r\n<li>Carte graphique&nbsp;Int&eacute;gr&eacute;:&nbsp;Carte graphique Intel&reg; HD 620</li>\r\n<li>Ports :&nbsp;1 port USB 3.1 Type-C&trade; 1re g&eacute;n&eacute;ration (Power Delivery, DisplayPort&trade;)&nbsp;;2 ports USB 3.0 (1 pour le chargement)&nbsp;;1&nbsp;port HDMI 1.4b&nbsp;;1 port VGA&nbsp;;1 prise RJ-45&nbsp;;1 alimentation secteur ;1 prise combin&eacute;e casque/microphone&nbsp;</li>\r\n<li><strong>Audio</strong>&nbsp;:&nbsp;2 haut-parleurs st&eacute;r&eacute;o int&eacute;gr&eacute;s ;Baie &agrave; double microphone int&eacute;gr&eacute;e ;</li>\r\n<li><strong>Appareil photo&nbsp;</strong>: Webcam 720p HD</li>\r\nClavier : Clavier HP Premium, pleine largeur, r&eacute;sistant &agrave; l&rsquo;eau</ul>\r\n</ul>\r\n<ul>Sans fil :&nbsp;Combo Intel&reg; double bande sans fil AC 8265 802.11a/b/g/n/ac (2 x 2) Wi-Fi&reg; et Bluetooth&reg; 4.2</ul>\r\n<p>&nbsp;</p>",
                "quantity" => 10,
                "price" => 296000,
                "sale_price" => 250000,
                "status" => 1,
                "featured" => 0,
                "stock" => 2,
                "is_new" => 1,
                "product_image" => "8gZd0OIbMvAnfkRbbteJ6jJ8G.jpg",
                "created_at" => "2021-06-05 00:23:09",
                "updated_at" => "2021-06-05 00:23:09",
                "height" => NULL,
            ],
            [
                "id" => 30,
                "brand_id" => 0,
                "sku" => "HP017EL1LCSGMNAFAMZ",
                "name" => "Hp PC - 15,6\" - CORE � I7 - 8250U - 16Go -1To Gris - Clavier Retro-eclaire",
                "slug" => "hp-pc-156-core-i7-8250u-16go-1to-gris-clavier-retro-eclaire",
                "description" => NULL,
                "caracteristique" => "<article class=\"col8 -pvs\">\r\n<div class=\"card-b -fh\">\r\n<div class=\"markup -pam\">\r\n<ul>\r\n<li>Nom du produit : HP Pavilion - 15-cs0057od</li>\r\n<li>Microprocesseur : Intel&reg; Core&trade; i7-8250U</li>\r\n<li>M&eacute;moire, standard : 16 GB DDR4-2400 SDRAM ( 4+ 8 GB)</li>\r\n<li>Graphiques vid&eacute;o : Intel UHD Graphics 620</li>\r\n<li>Disque dur : 1 To 5400 tpm SATA</li>\r\n<li>Ecran : 15.6 diagonal HD SVA WLED-backlit T (1366x768)</li>\r\n<li>Clavier : Clavier &icirc;lot pleine grandeur avec pav&eacute; num&eacute;rique int&eacute;gr&eacute;</li>\r\n<li>Dispositif de pointage : Pav&eacute; tactile avec prise en charge de gestes multi-touch</li>\r\n<li>Connectivit&eacute; sans fil : Intel 802.11ac (1x1) et Bluetooth&reg; 4.0 Combo</li>\r\n<li>Interface r&eacute;seau : LAN Ethernet 10/100 BASE-T int&eacute;gr&eacute;</li>\r\n<li>Ports externes : 1 HDMI; 1 combo casque / microphone; 2 USB 2.0; 1 USB 3.0; 1 RJ-45</li>\r\n<li>Dimensions minimales : 37.8 x 25.21 x 2.25 cm</li>\r\n<li><em>Poids</em>&nbsp;du produit : 2 Kg.</li>\r\n<li>Type d'alimentation : Adaptateur secteur 90W AC</li>\r\n<li>Type de batterie : 3 cellules, 41 Wh Li-ion</li>\r\n<li>Webcam : Webcam HP TrueVision HD (face &agrave; l'avant) avec microphone num&eacute;rique int&eacute;gr&eacute;</li>\r\n<li>Caract&eacute;ristiques audio :B&amp;O PLAY &trade; avec 2 haut-parleurs</li>\r\n<li>Syst&egrave;me d'exploitation : Windows 10 Pro</li>\r\n</ul>\r\n</div>\r\n</div>\r\n</article>\r\n<article class=\"col8 -pvs\">\r\n<div class=\"card-b -fh\">&nbsp;</div>\r\n</article>",
                "quantity" => 12,
                "price" => 579000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 2,
                "is_new" => 1,
                "product_image" => "bA9oMNfVlYtv9woCaHeP0iFyD.jpg",
                "created_at" => "2021-06-05 00:27:53",
                "updated_at" => "2021-06-05 00:27:53",
                "height" => NULL,
            ],
            [
                "id" => 31,
                "brand_id" => 0,
                "sku" => "HP017CL0V2WFLNAFAMZ",
                "name" => "Lenovo Ideapad V14 - 1000Go - 14? - RAM 4Go - Dual Core - Gris - Garantie 6 Mois - Sac Offert",
                "slug" => "lenovo-ideapad-v14-1000go-14-ram-4go-dual-core-gris-garantie-6-mois-sac-offert",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>Couleur</li>\r\n<li>Gris</li>\r\n<li>Processeur</li>\r\n<li>Processeur Dual&nbsp;Core Intel Celeron N4020 cadenc&eacute; &agrave; 1,1&nbsp;GHz (Boost 2,8&nbsp;GHz)&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</li>\r\n<li>4 Mo de m&eacute;moire cache</li>\r\n<li>M&eacute;moire</li>\r\n<li>4 Go de SDRAM DDR4 &agrave; 2400&nbsp;MHz</li>\r\n<li>Stockage</li>\r\n<li>Disque HDD de 1000Go</li>\r\n<li>Lecteur optique</li>\r\n<li>Aucun</li>\r\n<li>Affichage</li>\r\n<li>Ecran LED IPS&nbsp;mat de 14\" (35,56 cm)</li>\r\n<li>R&eacute;solution HD en 1366&nbsp;x 768&nbsp;pixels</li>\r\n<li>Rapport d'aspect 16:9</li>\r\n<li>Carte graphique</li>\r\n<li>Intel UHD Graphics 600</li>\r\n<li>Webcam</li>\r\n<li>Webcam VGA</li>\r\n<li>AudioHauts parleurs st&eacute;r&eacute;o</li>\r\n<li>Connectivit&eacute;Wi-Fi 802.11 a/b/g/n/ac</li>\r\n<li>Bluetooth v4.2</li>\r\n<li>Interfaces2 ports USB 3.0</li>\r\n<li>1 port HDMI</li>\r\n<li>1 prise combo casque/microphone</li>\r\n<li>1 lecteur de cartes micro SD</li>\r\n<li>Pas de port RJ45</li>\r\n<li>P&eacute;riph&eacute;riques d'entr&eacute;ePav&eacute; tactile multi-touches</li>\r\n</ul>",
                "quantity" => 10,
                "price" => 206000,
                "sale_price" => 199000,
                "status" => 1,
                "featured" => 0,
                "stock" => NULL,
                "is_new" => 1,
                "product_image" => "6ufeMHyBLU8Mkdnb14ntHaTAK.jpg",
                "created_at" => "2021-06-05 00:29:48",
                "updated_at" => "2021-06-05 00:29:48",
                "height" => NULL,
            ],
            [
                "id" => 32,
                "brand_id" => 0,
                "sku" => "AS040CL0CQG75NAFAMZ",
                "name" => "Asus Vivobook E410M - 128Go - 4Go - 14'' - Dual Core - Win10 - Blanc - Garantie 6 Mois - Sac Offert",
                "slug" => "asus-vivobook-e410m-128go-4go-14-dual-core-win10-blanc-garantie-6-mois-sac-offert",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>Ecran&nbsp;14.0'' FULL HD&nbsp;</li>\r\n<li>Processeur:&nbsp;&nbsp;Intel Celeron N4020&nbsp;(&nbsp;1.10 GHz&nbsp;Up to&nbsp;2.80 GHz,&nbsp;4Mo&nbsp;M&eacute;moire cache,&nbsp;Dual-Core)</li>\r\n<li>Windows 10&nbsp;</li>\r\n<li>M&eacute;moire RAM:&nbsp;4 Go&nbsp;</li>\r\n<li>Disque Dur:&nbsp;128 Go eMMC&nbsp;</li>\r\n<li>Carte Graphique:&nbsp;Intel HD Graphics&nbsp;</li>\r\n<li>Clavier Chiclet avec pav&eacute; tactile, num&eacute;rique et&nbsp;r&eacute;tro&eacute;clair&eacute;&nbsp;</li>\r\n<li>&nbsp;Wi-Fi, Bluetooth, Cam&eacute;ra Web et VGA</li>\r\n<li>&nbsp;Couleur: Bleu&nbsp;</li>\r\n<li>USB : 1 x USB 2.0, 1 x USB 3.1 , 1 x USB 3.1 Type C</li>\r\n<li>Lecteur de carte SD : x1</li>\r\n<li>Pas de Lecteur CD</li>\r\n</ul>",
                "quantity" => 10,
                "price" => 229900,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 3,
                "is_new" => 1,
                "product_image" => "067lHOTWvtOnXPyRsHEM8BVIh.jpg",
                "created_at" => "2021-06-05 00:31:32",
                "updated_at" => "2021-06-05 00:31:32",
                "height" => NULL,
            ],
            [
                "id" => 33,
                "brand_id" => 0,
                "sku" => "HP017CL1CVD2HNAFAMZ",
                "name" => "Hp Pc 15-Dw - DUAL CORE - 4Go Ram - 500Go Disque - Rouge",
                "slug" => "hp-pc-15-dw-dual-core-4go-ram-500go-disque-rouge",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>Type produit : Ordinateur portable</li>\r\n<li>Mod&egrave;le15-dw0081wm</li>\r\n<li>Webcam int&eacute;gr&eacute;e, microphone int&eacute;gr&eacute;, Bluetooth</li>\r\n<li>Taille de l'&eacute;cran 15,6 dans</li>\r\n<li>Processeur Intel Pentium</li>\r\n<li>Syst&egrave;me op&eacute;rateur Windows 10</li>\r\n<li>R&eacute;solution maximale 1 366 x 768</li>\r\n<li>Taille de la RAM4 GO</li>\r\n<li>Couleur du fabricant Couvercle et base rouge &eacute;carlate, cadre de clavier argent&eacute; naturel</li>\r\n<li>Capacit&eacute; du disque dur 500 Go</li>\r\n<li>La vitesse du processeur 2,40 GHz</li>\r\n<li>GPU Carte graphique Intel UHD 605</li>\r\n</ul>",
                "quantity" => 10,
                "price" => 248000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => NULL,
                "is_new" => 1,
                "product_image" => "nLlcAS729U4VEtLVP1zro6Z7F.jpg",
                "created_at" => "2021-06-05 00:33:38",
                "updated_at" => "2021-06-05 00:33:38",
                "height" => NULL,
            ],
            [
                "id" => 34,
                "brand_id" => 0,
                "sku" => "HP017CL122ME5NAFAMZ",
                "name" => "Hp Ordinateur De Bureau ProDesk 400G2 MT- 21\" - 4Go Ram - 500 Go - Dual Core - Noir - Garantie 6 Mois",
                "slug" => "hp-ordinateur-de-bureau-prodesk-400g2-mt-21-4go-ram-500-go-dual-core-noir-garantie-6-mois",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>FAMILLE DE PROCESSEUR Intel&nbsp;</li>\r\n<li>M&Eacute;MOIRE VIVE 4Go (4096Mo)</li>\r\n<li>TYPE DE M&Eacute;MOIRE DDR3</li>\r\n<li>DISQUE DUR 500Go</li>\r\n<li>VITESSE DU DISQUE DUR 7200trs/min</li>\r\n<li>FORMAT DU DISQUE DUR</li>\r\n<li>TAILLE D'&Eacute;CRAN 21 Pouces</li>\r\n<li>CONTR&Ocirc;LEUR GRAPHIQUE Intel HD Graphics 4400 (int&eacute;gr&eacute; au processeur)</li>\r\n<li>LECTEUR OPTIQUE Lecteur / Graveur DVD</li>\r\n<li>CONNEXION FILAIRE Ethernet Gigabit (RJ45) 10/100/1000Mbps</li>\r\n<li>PORT(S) USB 2.0 4</li>\r\n<li>PORT(S) USB 3.0 2</li>\r\n<li>PORT(S) DVI 1</li>\r\n<li>PORT(S) RJ45 1</li>\r\n<li>PRISE MICROPHONE 1</li>\r\n<li>PRISE CASQUE 1</li>\r\n<li>CLAVIER Fran&ccedil;ais AZERTY Avec Pav&eacute; Num&eacute;rique</li>\r\n<li>SYST&Egrave;ME D'EXPLOITATION Windows 10 conseille</li>\r\n</ul>",
                "quantity" => 10,
                "price" => 235000,
                "sale_price" => 210000,
                "status" => 1,
                "featured" => 0,
                "stock" => 2,
                "is_new" => 1,
                "product_image" => "tSS0O12C8vMxXFRmxyI8abNoo.jpg",
                "created_at" => "2021-06-05 00:36:58",
                "updated_at" => "2021-06-05 00:36:58",
                "height" => NULL,
            ],
            [
                "id" => 35,
                "brand_id" => 0,
                "sku" => "HP017SE0S0YEPNAFAMZ",
                "name" => "Hp Ordinateur De Bureau ProDesk 400 G7 Microtower - 1000Go - 4Go Ram - 21\" - Core I5 - Garantie 6 Mois",
                "slug" => "hp-ordinateur-de-bureau-prodesk-400-g7-microtower-1000go-4go-ram-21-core-i5-garantie-6-mois",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>Processeur&nbsp;Intel&reg; Core&trade; i5</li>\r\n<li>M&eacute;moire vive(RAM) install&eacute;e&nbsp;4 Go</li>\r\n<li>Taille du disque dur&nbsp;1 To</li>\r\n<li>Type du disque dur&nbsp;SATA</li>\r\n<li>Vitesse de rotation du disque dur&nbsp;7200 tours/min</li>\r\n<li>Lecteur / Graveur&nbsp;Graveur de DVD</li>\r\n<li>Carte graphique&nbsp;Intel&reg; UHD 630</li>\r\n<li>R&eacute;solution maxi&nbsp;1920 x 1080</li>\r\n<li>Poids en kg&nbsp;5 kg</li>\r\n<li>Taille de l'&eacute;cran&nbsp;20,7\"</li>\r\n<li>Type de l'&eacute;cran&nbsp;Full HD (1920 x 1080], IPS, anti-reflet, 250 nits, 45 % NTSC</li>\r\n<li>Audio&nbsp;Codec Realtek ALC3205, haut-parleur interne 2 W, prise audio universelle, prise combin&eacute;e micro/casque</li>\r\n<li>Clavier&nbsp;Clavier filaire USB HP (Fran&ccedil;ais AZERTY)</li>\r\n<li>Connecteurs&nbsp;1 prise combin&eacute;e casque/microphone; 2 port USB Type-A SuperSpeed, vitesse de transfert de 10 Gbit/s; 2 ports USB Type-A, vitesse de transfert de 480 Mbit/s</li>\r\n<li>1 sortie audio; 1 prise d&rsquo;alimentation; 1 port RJ-45; 1 port HDMI 1.4; 3 ports USB Type-A SuperSpeed, vitesse de transfert de 5 Gbit/s; 1 port DisplayPort&trade; 1.4; 2 ports USB Type-A, vitesse de transfert de 480 Mbit/s</li>\r\n<li>P&eacute;riph&eacute;rique de pointage&nbsp;Souris optique filaire USB HP</li>\r\n</ul>",
                "quantity" => 2,
                "price" => 249000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 1,
                "is_new" => 1,
                "product_image" => "intWIWIJpqTxHp7p2F90TPAop.jpg",
                "created_at" => "2021-06-05 00:38:50",
                "updated_at" => "2021-06-05 00:38:50",
                "height" => NULL,
            ],
            [
                "id" => 36,
                "brand_id" => 0,
                "sku" => "HP017EA0NQ2PPNAFAMZ",
                "name" => "Hp Ordinateur Bureau Pro 6300 MT - 21\" - Core I3 - 500GB - 4GB - FreeDOS - Noir - Garantie12 Mois",
                "slug" => "hp-ordinateur-bureau-pro-6300-mt-21-core-i3-500gb-4gb-freedos-noir-garantie12-mois",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>Processeur :&nbsp;Intel Core i3</li>\r\n<li>M&eacute;moire RAM install&eacute;e :&nbsp;4Go DDR3&nbsp;</li>\r\n<li>Emplacements RAM :&nbsp;4</li>\r\n<li>Disque dur :&nbsp;500Go 3.5\" M&eacute;canique / Magn&eacute;tique SATA</li>\r\n<li>Lecteur optique :&nbsp;Graveur DVD</li>\r\n<li>Ports USB Fa&ccedil;ade :&nbsp;4x USB2</li>\r\n<li>Ports USB Arri&egrave;re :&nbsp;2x USB2 + 4x USB 3</li>\r\n<li>Socket processeur :&nbsp;FCLGA1155</li>\r\n<li>Profil carte accept&eacute; :&nbsp;Profil long standard</li>\r\n<li>Ports PCI :&nbsp;1</li>\r\n<li>Port SATA :&nbsp;4</li>\r\n<li>Port PS/2 :&nbsp;2</li>\r\n<li>Sorties audio :&nbsp;1x Avant + 1x Arri&egrave;re</li>\r\n<li>Entr&eacute;es audio :&nbsp;1x Avant + 1x Arri&egrave;re</li>\r\n<li>Chipset :&nbsp;Intel Q75 Express</li>\r\n<li>R&eacute;seau Ethernet :&nbsp;Intel 82579LM Gigabit Ethernet</li>\r\n<li>Syst&egrave;me d'exploitation :&nbsp;Microsoft Windows 10 Conseill&eacute;</li>\r\n<li>Dimensions en cms (L x H x P) :&nbsp;17.7 x 37.7 x 43.1</li>\r\n<li>Poids :&nbsp;2.025 Kg</li>\r\n</ul>",
                "quantity" => 20,
                "price" => 450000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 1,
                "stock" => 10,
                "is_new" => 0,
                "product_image" => "4TW2gUFns7myYZCdFxUAaqBqd.jpg",
                "created_at" => "2021-06-05 00:40:39",
                "updated_at" => "2021-06-05 00:40:39",
                "height" => NULL,
            ],
            [
                "id" => 37,
                "brand_id" => 0,
                "sku" => "LE018CL04LIZDNAFAMZ",
                "name" => "Lenovo Tout En Un - Core I5-8100T - Ram 4 Go Sdram - Disque Dur 1 To + 16 Go Optane Memory- Gris",
                "slug" => "lenovo-tout-en-un-core-i5-8100t-ram-4-go-sdram-disque-dur-1-to-16-go-optane-memory-gris",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li><strong>T</strong>ype de produit : complet bureau</li>\r\n<li>Mod&egrave;le : ideacenter AIO 520</li>\r\n<li>Microprocesseur : Intel&reg; Core &trade; i3-8100T&nbsp;</li>\r\n<li>M&eacute;moire : 4 Go SDRAM</li>\r\n<li>M&eacute;moire du disque dur : 1 To + 16 Go optane memory</li>\r\n<li>Affichage : 22 pouces tactile</li>\r\n<li>clavier sans fil</li>\r\n<li>souris sans fil</li>\r\n</ul>",
                "quantity" => 2,
                "price" => 1000000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 1,
                "is_new" => 1,
                "product_image" => "H2TknGYjZt5eJATKtNaZuJmbg.jpg",
                "created_at" => "2021-06-05 00:42:32",
                "updated_at" => "2021-06-05 00:42:32",
                "height" => NULL,
            ],
            [
                "id" => 38,
                "brand_id" => 0,
                "sku" => "GE070CL01F6P9NAFAMZ",
                "name" => "PARTAGEZ CE PRODUIT   Support De Table Pliable Pour Ordinateur",
                "slug" => "partagez-ce-produit-support-de-table-pliable-pour-ordinateur",
                "description" => "<p><strong>DEUX GROS VENTILATEURS INT&Eacute;GR&Eacute;S:</strong><br />le puissant ventilateur du processeur r&eacute;duira la temp&eacute;rature de fonctionnement de votre ordinateur portable et fournira un flux d'air constant autour de lui.&nbsp;Il utilise des m&eacute;thodes de refroidissement actives pour r&eacute;partir l'air silencieusement et uniform&eacute;ment sous la base de votre ordinateur portable ou note-book.&nbsp;<strong>AJUSTEZ TOUT ANGLE:</strong>&nbsp;Ce support pour ordinateur portable avec des articulations &agrave; verrouillage automatique r&eacute;glables qui sont disponibles pour une rotation d'environ 360 degr&eacute;s.&nbsp;Il peut contenir des objets dans une vari&eacute;t&eacute; de configurations.&nbsp;La table fournira l'angle de frappe le plus confortable lorsque vous &ecirc;tes assis sur une chaise ou allong&eacute; sur le lit.&nbsp;<strong>JOINTS &Agrave; 360 DEGR&Eacute;S: Conception</strong>&nbsp;ergonomique avec support d'ordinateur portable &agrave; rotation r&eacute;glable &agrave; 360 degr&eacute;s.&nbsp;Ajustez l'&eacute;cran de votre ordinateur portable au meilleur niveau de vue pour prot&eacute;ger votre corps de la douleur au cou et de la pression des &eacute;paules.&nbsp;<strong>Bureau pour ordinateur portable pour lit.</strong><strong>&Eacute;tirez-vous, bougez vos jambes et laissez le support ergonomique pour ordinateur portable positionner parfaitement votre &eacute;cran.&nbsp;Bureau pour ordinateur pour canap&eacute;&nbsp;Lounge sur le canap&eacute; et calculez confortablement avec ce support d'ordinateur portable rafra&icirc;chissant.&nbsp;Support ergonomique pour ordinateur portable pour s'asseoir &agrave; un bureau&nbsp;Asseyez-vous droit et r&eacute;duisez l'&eacute;blouissement de l'&eacute;cran en tenant votre ordinateur portable &agrave; la hauteur parfaite.&nbsp;Support de&nbsp;bureau debout simple pour ordinateur portable&nbsp;Tenez-vous debout et travaillez &agrave; n'importe quelle table - ce bureau debout ergonomique pour ordinateur portable soul&egrave;ve des &eacute;crans jusqu'&agrave; 18 \"et comprend un tapis de souris.</strong></p>",
                "caracteristique" => "<ul>\r\n<li>PLATEAU EN ALUMINIUM VENTIL&Eacute; - Garde votre ordinateur portable au frais et la l&egrave;vre avant &eacute;paisse maintiendra les ordinateurs portables de toute taille en place</li>\r\n<li>PLATEAU EN ALUMINIUM EXTRA LARGE - Permet de placer la souris, la tablette ou le t&eacute;l&eacute;phone &agrave; c&ocirc;t&eacute; de votre ordinateur portable pour un acc&egrave;s rapide et pratique.</li>\r\n<li>&nbsp;PIEDS ENTI&Egrave;REMENT R&Eacute;GLABLES - Faites pivoter &agrave; 360 degr&eacute;s et verrouillez-le &agrave; diff&eacute;rents angles. R&eacute;duisez rapidement le support pour le rendre portable.</li>\r\n<li>UTILISATIONS MULTIPLES - La table peut &eacute;galement &ecirc;tre utilis&eacute;e pour un plateau de d&icirc;ner TV, un projecteur, un bureau debout, un plateau de livre, un bureau et un support de tablette</li>\r\n</ul>",
                "quantity" => 10,
                "price" => 33500,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 1,
                "stock" => 2,
                "is_new" => 0,
                "product_image" => "M8lrHkipHhBwL5Wi9jBnHmX6h.jpg",
                "created_at" => "2021-06-05 00:45:45",
                "updated_at" => "2021-06-05 00:45:45",
                "height" => NULL,
            ],
            [
                "id" => 39,
                "brand_id" => 0,
                "sku" => "AC008CL11BV75NAFAMZ",
                "name" => "Acer Tout En Un- 21\" Core I5 /8GB RAM/1TB HDD+256GB SSD Avec Clavier Souris Sans Fil",
                "slug" => "acer-tout-en-un-21-core-i5-8gb-ram1tb-hdd256gb-ssd-avec-clavier-souris-sans-fil",
                "description" => NULL,
                "caracteristique" => NULL,
                "quantity" => 20,
                "price" => 600000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 1,
                "stock" => 2,
                "is_new" => 1,
                "product_image" => "UQI12ri7ezMY0DnKYlnYiWYmE.jpg",
                "created_at" => "2021-06-05 00:50:06",
                "updated_at" => "2021-06-05 00:50:06",
                "height" => NULL,
            ],
            [
                "id" => 40,
                "brand_id" => 0,
                "sku" => "HP017EL0D0ET5NAFAMZ",
                "name" => "Hp �cran D'ordinateur 24es - 24\" - Noir/Gris",
                "slug" => "hp-ecran-dordinateur-24es-24-noirgris",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>23,8 pouces (60,4 cm)&nbsp;</li>\r\n<li>1920 x 1080 (Full HD)&nbsp;</li>\r\n<li>Affichage 7 ms (Standard)</li>\r\n<li>1 HDMI - 1 VGA (PC)</li>\r\n<li>Le + : Design &eacute;l&eacute;gant et sans contour d'&eacute;cran&nbsp;</li>\r\n</ul>",
                "quantity" => 2,
                "price" => 139000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 1,
                "is_new" => 1,
                "product_image" => "HX7EXaMVPVXDmkvWOjXoTHOLZ.jpg",
                "created_at" => "2021-06-05 00:52:00",
                "updated_at" => "2021-06-05 00:52:00",
                "height" => NULL,
            ],
            [
                "id" => 41,
                "brand_id" => 0,
                "sku" => "HP017CL0IDX75NAFAMZ",
                "name" => "Hp Ordinateur De Bureau 290 G1 - 20 Pouces - Dual Core 500 Gb HDD - 4 Gb RAM -FreeDos - Noir",
                "slug" => "hp-ordinateur-de-bureau-290-g1-20-pouces-dual-core-500-gb-hdd-4-gb-ram-freedos-noir",
                "description" => "<ul>\r\n<li>Type de produit : Ordinateur De Bureau</li>\r\n<li>Mod&egrave;le : 290 G1</li>\r\n<li>Ecran : 20 Pouces&nbsp;</li>\r\n<li>Processeur: Intel Dual&nbsp; , 3.2 Ghz , 3 Mo de m&eacute;moire cache</li>\r\n<li>Stockage Disque dur : 500 Go</li>\r\n<li>M&eacute;moire Ram : 4 Go</li>\r\n<li>Syst&egrave;me d'exploitation : Free Dos (PC sans syst&egrave;me d'exploitation avec une version d'essai Windows 10 pr&eacute;-install&eacute;e valable 1 Mois)</li>\r\n<li>Lecteurs/Graveurs :&nbsp;</li>\r\n<li>Carte graphique: Intel HD Graphics</li>\r\n<li>Connectivit&eacute;s : 6xUSB 2.0 , 1xDVI , 1xVGA , 1xRJ-45 , 1xEntr&eacute;e Micro</li>\r\n<li>Clavier: USB , Azerty</li>\r\n<li>Souris: USB , Optique</li>\r\n<li>Dimensions : 35.5 x 16.5 x 35.9 cm</li>\r\n<li>Poids : 13 Kg</li>\r\n</ul>",
                "caracteristique" => "<p>Type de produit : Ordinateur De BureauMod&egrave;le : 290 G1Ecran : 20 Pouces&nbsp;Processeur: Intel Dual&nbsp; , 3.2 Ghz , 3 Mo de m&eacute;moire cacheStockage Disque dur : 500 GoM&eacute;moire Ram : 4 GoSyst&egrave;me d'exploitation : Free Dos (PC sans syst&egrave;me d'exploitation avec une version d'essai Windows 10 pr&eacute;-install&eacute;e valable 1 Mois)Lecteurs/Graveurs :&nbsp;Carte graphique: Intel HD GraphicsConnectivit&eacute;s : 6xUSB 2.0 , 1xDVI , 1xVGA , 1xRJ-45 , 1xEntr&eacute;e MicroClavier: USB , AzertySouris: USB , OptiqueDimensions : 35.5 x 16.5 x 35.9 cmPoids : 13 Kg</p>",
                "quantity" => 6,
                "price" => 299000,
                "sale_price" => 289000,
                "status" => 1,
                "featured" => 1,
                "stock" => 1,
                "is_new" => 0,
                "product_image" => "wcKGcskQtAqNsUfiR1aUe9Lyn.jpg",
                "created_at" => "2021-06-05 00:55:08",
                "updated_at" => "2021-06-05 00:55:08",
                "height" => NULL,
            ],
            [
                "id" => 42,
                "brand_id" => 0,
                "sku" => "CA011EL14AS6RNAFAMZ",
                "name" => "Canon PIXMA G2411 - Imprimante Jet D'Encre Multifonction - Noir",
                "slug" => "canon-pixma-g2411-imprimante-jet-dencre-multifonction-noir",
                "description" => "<p>Imprimez en haute qualit&eacute; gr&acirc;ce &agrave; la technologie FINE de Canon et au syst&egrave;me d'encre hybride, dot&eacute; d'un pigment noir pour des documents nets et de couleurs &agrave; base de colorants pour des photos &eacute;clatantes sans bordure jusqu'au format&nbsp;A4.Ce multifonction compact avec fonctions d'impression, de copie et de num&eacute;risation traite de grands volumes d'impression en toute simplicit&eacute; gr&acirc;ce &agrave; son syst&egrave;me d'encre&nbsp;FINE r&eacute;sistant. La solution id&eacute;ale pour les particuliers et les petites entreprises.</p>",
                "caracteristique" => "<ul>\r\n<li>Garantie</li>\r\n<li>Rendement &eacute;lev&eacute;</li>\r\n<li>Impression sans marge</li>\r\n<li>Alimentation papier arri&egrave;re</li>\r\n<li>R&eacute;servoirs d'encre int&eacute;gr&eacute;s</li>\r\n<li>Mise sous tension automatique</li>\r\n<li>&Eacute;cran LCD 1,2&rdquo;</li>\r\n<li>Syst&egrave;me d'encre hybride</li>\r\n<li>Texte noir extr&ecirc;mement net</li>\r\n<li>Environ 8,8&nbsp;ipm</li>\r\n<li>Vitesse d'impression en couleur</li>\r\n<li>Environ 5&nbsp;ipm</li>\r\n<li>Vitesse d'impression photo</li>\r\n<li>10&nbsp;&times;&nbsp;15&nbsp;cm sans marge&nbsp;: environ 60&nbsp;secondes</li>\r\n<li>Impression sans marge</li>\r\n<li>Oui (A4, Lettre, 20&nbsp;&times;&nbsp;25 cm, 13&nbsp;&times;&nbsp;18 cm, 13&nbsp;&times;&nbsp;13 cm,10&nbsp;&times;&nbsp;15 cm)</li>\r\n<li>Formats de papier<strong>&nbsp;:&nbsp;</strong>A4, A5, B5, 10&nbsp;&times;&nbsp;15&nbsp;cm, 13&nbsp;&times;&nbsp;18&nbsp;cm, 20&nbsp;&times;&nbsp;25&nbsp;cm, Enveloppes (DL, COM10], Lettre, L&eacute;gal</li>\r\n<li>Syst&egrave;mes d'exploitation pris en charge</li>\r\n<li>Windows&nbsp;10, Windows&nbsp;8.1, Windows&nbsp;7&nbsp;SP1</li>\r\n<li>.NET&nbsp;Framework&nbsp;4.5.2 ou&nbsp;4.6 est requis</li>\r\n<li>Courant alternatif&nbsp;: 100 &agrave; 240&nbsp;V, 50&nbsp;/&nbsp;60&nbsp;Hz</li>\r\n<li>Hors tension&nbsp;: environ 0,2&nbsp;W</li>\r\n<li>Mode veille (reli&eacute; &agrave; l'ordinateur en USB)&nbsp;: environ 0,6&nbsp;W (lampe de num&eacute;risation &eacute;teinte)</li>\r\n<li>Mode veille (tous les ports connect&eacute;s)&nbsp;: environ 0,6&nbsp;W (lampe de num&eacute;risation &eacute;teinte)</li>\r\n<li>D&eacute;lai de passage en mode de veille&nbsp;: 10&nbsp;min 48&nbsp;s</li>\r\n<li>Copie&nbsp;: environ 9 W&nbsp;</li>\r\n<li>Livr&eacute; sans c&acirc;ble</li>\r\n<li>Les cartouches couleurs ne sont pas livr&eacute;es.</li>\r\n</ul>",
                "quantity" => 10,
                "price" => 148000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 1,
                "stock" => 2,
                "is_new" => 1,
                "product_image" => "By29ZGu4yqMW55Gm3o3RgxOrP.jpg",
                "created_at" => "2021-06-05 00:58:32",
                "updated_at" => "2021-06-05 00:58:32",
                "height" => NULL,
            ],
            [
                "id" => 43,
                "brand_id" => 0,
                "sku" => "HP017EL0QFBK9NAFAMZ",
                "name" => "Hp Imprimante 2710 - Wifi - Impression - Photocopie - Scanner - Blanc",
                "slug" => "hp-imprimante-2710-wifi-impression-photocopie-scanner-blanc",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>Type de sortie d'imprimante Monochrome</li>\r\n<li>Couleur Blanc</li>\r\n<li>Marque HP</li>\r\n<li>Type de m&eacute;dia d'impression Envelopes, Paper (plain)</li>\r\n<li>Type de connecteur Wi-Fi</li>\r\n<li>s&eacute;ries DeskJet 2710</li>\r\n<li>Syst&egrave;me d'exploitation MacOS 10.12 Sierra, MacOS 10.14 Mojave, Windows 7, MacOS 10.13 High Sierra</li>\r\n<li>Interface du mat&eacute;riel informatique USB 2.0</li>\r\n<li>Capacit&eacute; de stockage 512 MB</li>\r\n<li>Capacit&eacute; maximale en papier (entr&eacute;e) 60</li>\r\n</ul>",
                "quantity" => 10,
                "price" => 550000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 3,
                "is_new" => 1,
                "product_image" => "zy3gbhpPnQgWp0AIOPnBEHCUH.jpg",
                "created_at" => "2021-06-05 01:00:00",
                "updated_at" => "2021-06-05 01:00:00",
                "height" => NULL,
            ],
            [
                "id" => 44,
                "brand_id" => 0,
                "sku" => "GE070EA1NDONRNAFAMZ",
                "name" => "Imprimante Thermique - 58mm Pour Re�u",
                "slug" => "imprimante-thermique-58mm-pour-recu",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>Type de produit : Imprimante de Re&ccedil;us&nbsp;</li>\r\n<li>Vitesse d'impression: 90 mm / sec</li>\r\n<li>Largeur du papier: 58 mm</li>\r\n<li>Densit&eacute; d'impression: 384 points / ligne</li>\r\n<li>Papier d'impression &eacute;pais: 0,06-0,08 mm</li>\r\n<li>Type d'interface: USB</li>\r\n</ul>",
                "quantity" => 2,
                "price" => 47000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 1,
                "is_new" => 1,
                "product_image" => "ACk79yU5yk1QCc6a2uCX2W0WX.jpg",
                "created_at" => "2021-06-05 01:01:39",
                "updated_at" => "2021-06-05 01:01:39",
                "height" => NULL,
            ],
            [
                "id" => 45,
                "brand_id" => 0,
                "sku" => "HP017EA0OYLBVNAFAMZ",
                "name" => "Hp Imprimante Multifonction HP LaserJet Pro M428fdw-BLANC",
                "slug" => "hp-imprimante-multifonction-hp-laserjet-pro-m428fdw-blanc",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>Imprimante multifonction noir et blanc - Id&eacute;al pour les PME</li>\r\n<li>Impression, Copie, Num&eacute;risation, T&eacute;l&eacute;copie, E-mail</li>\r\n<li>Bac 1 : A4; A5; A6; B5 (JIS); Oficio (216 x 340 mm); 16K (195 x 270 mm); 16K (184 x 260 mm); 16K (197 x 273 mm); Enveloppe n&deg;10; Enveloppe Monarch; Enveloppe B5; Enveloppe C5; Enveloppe DL; Format personnalis&eacute;; Statement; Bacs d'alimentation 2 et 3 : A4; A5; A6; B5 (JIS); Oficio (216 x 340 mm); 16K (195 x 270 mm); 16K (184 x 260 mm); 16K (197 x 273 mm); Format personnalis&eacute;; A5-R; B6 (JIS)</li>\r\n<li>1 port USB 2.0 haut d&eacute;bit; 1 port h&ocirc;te USB arri&egrave;re; 1 port USB avant; R&eacute;seau Gigabit Ethernet LAN 10/100/1000 BASE-T; 802.11b/g/n/2.4/5 GHZ Radio Wi-Fi</li>\r\n<li>Jusqu'&agrave; 80 000 page</li>\r\n</ul>",
                "quantity" => 15,
                "price" => 290000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 5,
                "is_new" => 1,
                "product_image" => "ixc7tItCStOBpTr2XoCH4D9VW.jpg",
                "created_at" => "2021-06-05 01:03:18",
                "updated_at" => "2021-06-05 01:03:18",
                "height" => NULL,
            ],
            [
                "id" => 46,
                "brand_id" => 0,
                "sku" => "CA011EL0B4MR6NAFAMZ",
                "name" => "Canon Imprimante Multifonction Canon TS3140 Wi-Fi - InkJet MFP / A4 / 8 Ppm - Noir",
                "slug" => "canon-imprimante-multifonction-canon-ts3140-wi-fi-inkjet-mfp-a4-8-ppm-noir",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>ype de produit : Imprimante</li>\r\n<li>Mod&egrave;le : TS3140</li>\r\n<li>Fonctions : Wi-Fi, Impression, copie, num&eacute;risation, cloud</li>\r\n<li>Technologie d'impression : jet d'encre</li>\r\n<li>Nombre de cartouches d'impression : 2 cartouches FINE (noir et couleur)</li>\r\n<li>Ecran LCD de 3,8 cm monochrome</li>\r\n<li>Vitesse d'impression : Jusqu'&agrave; 7,7 ppm Noir ISO (A4], Jusqu'&agrave; 4 ppm Couleur ISO (A4)</li>\r\n<li>Recto-verso : Manuel</li>\r\n<li>Impression sans bordure : Oui (13x18cm, 10x15cm, 13x13cm)</li>\r\n<li>R&eacute;solution d'impression : jusqu'&agrave; 4800 x 1200 ppp</li>\r\n</ul>",
                "quantity" => 12,
                "price" => 55000,
                "sale_price" => 47350,
                "status" => 1,
                "featured" => 0,
                "stock" => 2,
                "is_new" => 1,
                "product_image" => "s40cxvR9xkLFiqoKgbWmEavme.jpg",
                "created_at" => "2021-06-05 01:04:45",
                "updated_at" => "2021-06-05 01:04:45",
                "height" => NULL,
            ],
            [
                "id" => 47,
                "brand_id" => 0,
                "sku" => "GE070EA0C97WLNAFAMZ",
                "name" => "Imprimante De Re�us Thermique Mini USB + Bluetooth",
                "slug" => "imprimante-de-recus-thermique-mini-usb-bluetooth",
                "description" => NULL,
                "caracteristique" => "<ul>\r\n<li>Impression sans fil.</li>\r\n<li>Large compatibilit&eacute;.</li>\r\n<li>Multi Codes pris en charge.</li>\r\n<li>Batterie 1800mAh.</li>\r\n<li>Mini taille.</li>\r\n<li>Op&eacute;ration facile.</li>\r\n<li>Impression thermique.</li>\r\n<li>Contr&ocirc;le du t&eacute;l&eacute;phone intelligent.</li>\r\n</ul>",
                "quantity" => 12,
                "price" => 29690,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 3,
                "is_new" => 1,
                "product_image" => "peAXLpyqsdsFHHSq6W1ZnDQ0S.jpg",
                "created_at" => "2021-06-05 01:06:34",
                "updated_at" => "2021-06-05 01:06:34",
                "height" => NULL,
            ],
            [
                "id" => 48,
                "brand_id" => 0,
                "sku" => "CA011EL0JZ49TNAFAMZ",
                "name" => "Canon Imprimante Multifonction Canon TS3140 Wi-Fi - Noir",
                "slug" => "canon-imprimante-multifonction-canon-ts3140-wi-fi-noir",
                "description" => NULL,
                "caracteristique" => NULL,
                "quantity" => 15,
                "price" => 39600,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 2,
                "is_new" => 1,
                "product_image" => "8a5QJISNTsJFGoLEapSaB8H1y.jpg",
                "created_at" => "2021-06-05 01:08:19",
                "updated_at" => "2021-06-05 01:08:19",
                "height" => NULL,
            ],
            [
                "id" => 49,
                "brand_id" => 0,
                "sku" => "HP017EA03KUM1NAFAMZ",
                "name" => "Hp Imprimante HP Laser Couleur 150a - BLANC",
                "slug" => "hp-imprimante-hp-laser-couleur-150a-blanc",
                "description" => NULL,
                "caracteristique" => NULL,
                "quantity" => 10,
                "price" => 126000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 2,
                "is_new" => 1,
                "product_image" => "xkMBqfqwSME9O5YIHWM35V9YR.jpg",
                "created_at" => "2021-06-05 01:12:21",
                "updated_at" => "2021-06-05 01:12:21",
                "height" => NULL,
            ],
            [
                "id" => 50,
                "brand_id" => 0,
                "sku" => "HP017EL1CHRMQNAFAMZ",
                "name" => "Hp Imprimante Multifonction LaserJet Pro MFP M130a - Blanc",
                "slug" => "hp-imprimante-multifonction-laserjet-pro-mfp-m130a-blanc",
                "description" => NULL,
                "caracteristique" => NULL,
                "quantity" => 3,
                "price" => 139000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 0,
                "stock" => 2,
                "is_new" => 1,
                "product_image" => "NpGiV7a3Vsccz3AbSmP70J4ZA.jpg",
                "created_at" => "2021-06-05 01:13:55",
                "updated_at" => "2021-06-05 01:13:55",
                "height" => NULL,
            ],
            [
                "id" => 51,
                "brand_id" => 0,
                "sku" => "GE070EA0507G3NAFAMZ",
                "name" => "Kit Recharge D'Encre 4 Couleurs 100ml - Noir/Rouge/Jaune/Bleu",
                "slug" => "kit-recharge-dencre-4-couleurs-100ml-noirrougejaunebleu",
                "description" => "<p><strong>REV&nbsp;&lsquo;COLOR</strong>, l&rsquo;encre universelle premium haute qualit&eacute; pour toutes vos impressions.</p>\r\n<p>Optez pour notre encre et soyez productif. Nous vous proposons un pack de 4 couleurs pour imprimantes jet d&rsquo;encre compatibles HP, Canon, Epson et Brother.</p>\r\n<p>Vous m&eacute;ritez le meilleur, choisissez&nbsp;<strong>REV&rsquo;COLOR</strong>&nbsp;et imprimez vos id&eacute;es.</p>\r\n<p><strong>REV&rsquo;COLOR</strong>&nbsp;est une marque sp&eacute;cialis&eacute;e dans la fabrication, la distribution et la vente d&rsquo;encre et consommables pour l&rsquo;impression.</p>",
                "caracteristique" => NULL,
                "quantity" => 120,
                "price" => 35000,
                "sale_price" => NULL,
                "status" => 1,
                "featured" => 1,
                "stock" => 3,
                "is_new" => 1,
                "product_image" => "D1nK1y2rIKWjUlxeNnveqoScD.jpg",
                "created_at" => "2021-06-05 01:16:04",
                "updated_at" => "2021-06-05 01:27:01",
                "height" => NULL,
            ],
        ];

        foreach($products as $product){
            Product::create($product);
        }


        $product_images = [
            [
                "id" => 17,
                "product_id" => 13,
                "full" => "bYYUncxRMpMjLrv5jj7aNhiAL.jpg",
                "created_at" => "2021-06-03 10:49:27",
                "updated_at" => "2021-06-03 10:49:27",
            ],
            [
                "id" => 21,
                "product_id" => 10,
                "full" => "UjvkBOm4xiZM1JZMzBeYUOiLu.jpg",
                "created_at" => "2021-06-03 13:47:58",
                "updated_at" => "2021-06-03 13:47:58",
            ],
            [
                "id" => 22,
                "product_id" => 10,
                "full" => "1nEIIxhGsEMz2ktOCM3yPJgaz.jpg",
                "created_at" => "2021-06-03 13:47:59",
                "updated_at" => "2021-06-03 13:47:59",
            ],
            [
                "id" => 23,
                "product_id" => 10,
                "full" => "l2gXNNEk43Kv3DcicRsexS2Vx.jpg",
                "created_at" => "2021-06-03 13:48:01",
                "updated_at" => "2021-06-03 13:48:01",
            ],
            [
                "id" => 24,
                "product_id" => 10,
                "full" => "YYb5qvFY1G25lfUDxZ1gn6rEl.jpg",
                "created_at" => "2021-06-03 13:56:12",
                "updated_at" => "2021-06-03 13:56:12",
            ],
            [
                "id" => 25,
                "product_id" => 10,
                "full" => "TA3lU2hPdDoE684ytxUpWqwdx.jpg",
                "created_at" => "2021-06-03 13:56:14",
                "updated_at" => "2021-06-03 13:56:14",
            ],
            [
                "id" => 26,
                "product_id" => 10,
                "full" => "c5KQpap58cWvScIdZ6Y67fBgO.jpg",
                "created_at" => "2021-06-03 13:56:16",
                "updated_at" => "2021-06-03 13:56:16",
            ],
        ];

        foreach($product_images as $image){
            ProductImage::create($image);
        }


        $product_categories = [
            [
                "id" => 1,
                "category_id" => 4,
                "product_id" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 2,
                "category_id" => 9,
                "product_id" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 3,
                "category_id" => 9,
                "product_id" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 4,
                "category_id" => 12,
                "product_id" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 5,
                "category_id" => 9,
                "product_id" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 6,
                "category_id" => 12,
                "product_id" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 7,
                "category_id" => 16,
                "product_id" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 8,
                "category_id" => 4,
                "product_id" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 9,
                "category_id" => 12,
                "product_id" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 10,
                "category_id" => 4,
                "product_id" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 11,
                "category_id" => 9,
                "product_id" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 12,
                "category_id" => 4,
                "product_id" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 13,
                "category_id" => 9,
                "product_id" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 14,
                "category_id" => 4,
                "product_id" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 15,
                "category_id" => 9,
                "product_id" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 16,
                "category_id" => 4,
                "product_id" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 17,
                "category_id" => 9,
                "product_id" => NULL,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 18,
                "category_id" => 4,
                "product_id" => 10,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 19,
                "category_id" => 9,
                "product_id" => 10,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 20,
                "category_id" => 12,
                "product_id" => 10,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 21,
                "category_id" => 4,
                "product_id" => 11,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 22,
                "category_id" => 9,
                "product_id" => 11,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 23,
                "category_id" => 12,
                "product_id" => 11,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 24,
                "category_id" => 4,
                "product_id" => 13,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 25,
                "category_id" => 9,
                "product_id" => 13,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 26,
                "category_id" => 12,
                "product_id" => 13,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 27,
                "category_id" => 4,
                "product_id" => 14,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 28,
                "category_id" => 9,
                "product_id" => 14,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 29,
                "category_id" => 14,
                "product_id" => 14,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 30,
                "category_id" => 4,
                "product_id" => 15,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 31,
                "category_id" => 9,
                "product_id" => 15,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 32,
                "category_id" => 15,
                "product_id" => 15,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 33,
                "category_id" => 17,
                "product_id" => 16,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 34,
                "category_id" => 18,
                "product_id" => 16,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 35,
                "category_id" => 22,
                "product_id" => 16,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 36,
                "category_id" => 17,
                "product_id" => 17,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 37,
                "category_id" => 18,
                "product_id" => 17,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 38,
                "category_id" => 21,
                "product_id" => 17,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 39,
                "category_id" => 17,
                "product_id" => 18,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 40,
                "category_id" => 18,
                "product_id" => 18,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 41,
                "category_id" => 21,
                "product_id" => 18,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 42,
                "category_id" => 17,
                "product_id" => 19,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 43,
                "category_id" => 18,
                "product_id" => 19,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 44,
                "category_id" => 21,
                "product_id" => 19,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 45,
                "category_id" => 17,
                "product_id" => 21,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 46,
                "category_id" => 18,
                "product_id" => 21,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 47,
                "category_id" => 21,
                "product_id" => 21,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 48,
                "category_id" => 17,
                "product_id" => 22,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 49,
                "category_id" => 18,
                "product_id" => 22,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 50,
                "category_id" => 21,
                "product_id" => 22,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 51,
                "category_id" => 17,
                "product_id" => 23,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 52,
                "category_id" => 18,
                "product_id" => 23,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 53,
                "category_id" => 22,
                "product_id" => 23,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 54,
                "category_id" => 17,
                "product_id" => 24,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 55,
                "category_id" => 18,
                "product_id" => 24,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 56,
                "category_id" => 22,
                "product_id" => 24,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 57,
                "category_id" => 17,
                "product_id" => 25,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 58,
                "category_id" => 18,
                "product_id" => 25,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 59,
                "category_id" => 22,
                "product_id" => 25,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 60,
                "category_id" => 17,
                "product_id" => 26,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 61,
                "category_id" => 18,
                "product_id" => 26,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 62,
                "category_id" => 22,
                "product_id" => 26,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 63,
                "category_id" => 17,
                "product_id" => 27,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 64,
                "category_id" => 18,
                "product_id" => 27,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 65,
                "category_id" => 22,
                "product_id" => 27,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 66,
                "category_id" => 48,
                "product_id" => 28,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 67,
                "category_id" => 49,
                "product_id" => 28,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 68,
                "category_id" => 50,
                "product_id" => 28,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 69,
                "category_id" => 48,
                "product_id" => 29,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 70,
                "category_id" => 49,
                "product_id" => 29,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 71,
                "category_id" => 50,
                "product_id" => 29,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 72,
                "category_id" => 48,
                "product_id" => 30,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 73,
                "category_id" => 49,
                "product_id" => 30,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 74,
                "category_id" => 50,
                "product_id" => 30,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 75,
                "category_id" => 48,
                "product_id" => 31,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 76,
                "category_id" => 49,
                "product_id" => 31,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 77,
                "category_id" => 50,
                "product_id" => 31,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 78,
                "category_id" => 48,
                "product_id" => 32,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 79,
                "category_id" => 49,
                "product_id" => 32,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 80,
                "category_id" => 50,
                "product_id" => 32,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 81,
                "category_id" => 48,
                "product_id" => 33,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 82,
                "category_id" => 49,
                "product_id" => 33,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 83,
                "category_id" => 50,
                "product_id" => 33,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 84,
                "category_id" => 48,
                "product_id" => 34,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 85,
                "category_id" => 49,
                "product_id" => 34,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 86,
                "category_id" => 52,
                "product_id" => 34,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 87,
                "category_id" => 48,
                "product_id" => 35,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 88,
                "category_id" => 49,
                "product_id" => 35,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 89,
                "category_id" => 52,
                "product_id" => 35,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 90,
                "category_id" => 48,
                "product_id" => 36,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 91,
                "category_id" => 49,
                "product_id" => 36,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 92,
                "category_id" => 52,
                "product_id" => 36,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 93,
                "category_id" => 48,
                "product_id" => 37,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 94,
                "category_id" => 49,
                "product_id" => 37,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 95,
                "category_id" => 52,
                "product_id" => 37,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 96,
                "category_id" => 48,
                "product_id" => 38,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 97,
                "category_id" => 49,
                "product_id" => 38,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 98,
                "category_id" => 52,
                "product_id" => 38,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 99,
                "category_id" => 60,
                "product_id" => 38,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 100,
                "category_id" => 65,
                "product_id" => 38,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 101,
                "category_id" => 48,
                "product_id" => 40,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 102,
                "category_id" => 49,
                "product_id" => 40,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 103,
                "category_id" => 52,
                "product_id" => 40,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 104,
                "category_id" => 53,
                "product_id" => 40,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 105,
                "category_id" => 48,
                "product_id" => 41,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 106,
                "category_id" => 49,
                "product_id" => 41,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 107,
                "category_id" => 50,
                "product_id" => 41,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 108,
                "category_id" => 48,
                "product_id" => 42,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 109,
                "category_id" => 54,
                "product_id" => 42,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 110,
                "category_id" => 55,
                "product_id" => 42,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 111,
                "category_id" => 48,
                "product_id" => 43,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 112,
                "category_id" => 54,
                "product_id" => 43,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 113,
                "category_id" => 56,
                "product_id" => 43,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 114,
                "category_id" => 48,
                "product_id" => 44,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 115,
                "category_id" => 54,
                "product_id" => 44,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 116,
                "category_id" => 56,
                "product_id" => 44,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 117,
                "category_id" => 48,
                "product_id" => 45,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 118,
                "category_id" => 54,
                "product_id" => 45,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 119,
                "category_id" => 56,
                "product_id" => 45,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 120,
                "category_id" => 48,
                "product_id" => 46,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 121,
                "category_id" => 54,
                "product_id" => 46,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 122,
                "category_id" => 56,
                "product_id" => 46,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 123,
                "category_id" => 48,
                "product_id" => 47,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 124,
                "category_id" => 54,
                "product_id" => 47,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 125,
                "category_id" => 55,
                "product_id" => 47,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 126,
                "category_id" => 48,
                "product_id" => 48,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 127,
                "category_id" => 54,
                "product_id" => 48,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 128,
                "category_id" => 55,
                "product_id" => 48,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 129,
                "category_id" => 48,
                "product_id" => 49,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 130,
                "category_id" => 54,
                "product_id" => 49,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 131,
                "category_id" => 55,
                "product_id" => 49,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 132,
                "category_id" => 48,
                "product_id" => 50,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 133,
                "category_id" => 54,
                "product_id" => 50,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 134,
                "category_id" => 55,
                "product_id" => 50,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 135,
                "category_id" => 48,
                "product_id" => 51,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 136,
                "category_id" => 54,
                "product_id" => 51,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
            [
                "id" => 137,
                "category_id" => 56,
                "product_id" => 51,
                "created_at" => NULL,
                "updated_at" => NULL,
            ],
        ];


        foreach($product_categories as $item){
            DB::table('product_categories')->insert($item);
        }
    }
}
